
/* Generated by generate_wrap_defines.py */
#ifndef __PY_WRAP_MPI_WRAPPER_H__
#define __PY_WRAP_MPI_WRAPPER_H__
#define event_MPI_Init 0
#define event_MPI_Finalize 1
#define event_MPI_Send 2
#define event_MPI_Recv 3
#define event_MPI_Irecv 4
#define event_MPI_Abort 5
#define event_MPI_Accumulate 6
#define event_MPI_Add_error_class 7
#define event_MPI_Add_error_code 8
#define event_MPI_Add_error_string 9
#define event_MPI_Address 10
#define event_MPI_Aint_add 11
#define event_MPI_Aint_diff 12
#define event_MPI_Allgather 13
#define event_MPI_Allgatherv 14
#define event_MPI_Alloc_mem 15
#define event_MPI_Allreduce 16
#define event_MPI_Alltoall 17
#define event_MPI_Alltoallv 18
#define event_MPI_Alltoallw 19
#define event_MPI_Attr_delete 20
#define event_MPI_Attr_get 21
#define event_MPI_Attr_put 22
#define event_MPI_Barrier 23
#define event_MPI_Bcast 24
#define event_MPI_Bsend 25
#define event_MPI_Bsend_init 26
#define event_MPI_Buffer_attach 27
#define event_MPI_Buffer_detach 28
#define event_MPI_Cancel 29
#define event_MPI_Cart_coords 30
#define event_MPI_Cart_create 31
#define event_MPI_Cart_get 32
#define event_MPI_Cart_map 33
#define event_MPI_Cart_rank 34
#define event_MPI_Cart_shift 35
#define event_MPI_Cart_sub 36
#define event_MPI_Cartdim_get 37
#define event_MPI_Close_port 38
#define event_MPI_Comm_accept 39
#define event_MPI_Comm_call_errhandler 40
#define event_MPI_Comm_compare 41
#define event_MPI_Comm_connect 42
#define event_MPI_Comm_create 43
#define event_MPI_Comm_create_errhandler 44
#define event_MPI_Comm_create_group 45
#define event_MPI_Comm_create_keyval 46
#define event_MPI_Comm_delete_attr 47
#define event_MPI_Comm_disconnect 48
#define event_MPI_Comm_dup 49
#define event_MPI_Comm_dup_with_info 50
#define event_MPI_Comm_free 51
#define event_MPI_Comm_free_keyval 52
#define event_MPI_Comm_get_attr 53
#define event_MPI_Comm_get_errhandler 54
#define event_MPI_Comm_get_info 55
#define event_MPI_Comm_get_name 56
#define event_MPI_Comm_get_parent 57
#define event_MPI_Comm_group 58
#define event_MPI_Comm_idup 59
#define event_MPI_Comm_join 60
#define event_MPI_Comm_rank 61
#define event_MPI_Comm_remote_group 62
#define event_MPI_Comm_remote_size 63
#define event_MPI_Comm_set_attr 64
#define event_MPI_Comm_set_errhandler 65
#define event_MPI_Comm_set_info 66
#define event_MPI_Comm_set_name 67
#define event_MPI_Comm_size 68
#define event_MPI_Comm_split 69
#define event_MPI_Comm_split_type 70
#define event_MPI_Comm_test_inter 71
#define event_MPI_Compare_and_swap 72
#define event_MPI_Dims_create 73
#define event_MPI_Dist_graph_create 74
#define event_MPI_Dist_graph_create_adjacent 75
#define event_MPI_Dist_graph_neighbors 76
#define event_MPI_Dist_graph_neighbors_count 77
#define event_MPI_Errhandler_create 78
#define event_MPI_Errhandler_free 79
#define event_MPI_Errhandler_get 80
#define event_MPI_Errhandler_set 81
#define event_MPI_Error_class 82
#define event_MPI_Error_string 83
#define event_MPI_Exscan 84
#define event_MPI_Fetch_and_op 85
#define event_MPI_File_call_errhandler 86
#define event_MPI_File_close 87
#define event_MPI_File_create_errhandler 88
#define event_MPI_File_delete 89
#define event_MPI_File_get_amode 90
#define event_MPI_File_get_atomicity 91
#define event_MPI_File_get_byte_offset 92
#define event_MPI_File_get_errhandler 93
#define event_MPI_File_get_group 94
#define event_MPI_File_get_info 95
#define event_MPI_File_get_position 96
#define event_MPI_File_get_position_shared 97
#define event_MPI_File_get_size 98
#define event_MPI_File_get_type_extent 99
#define event_MPI_File_get_view 100
#define event_MPI_File_iread 101
#define event_MPI_File_iread_all 102
#define event_MPI_File_iread_at 103
#define event_MPI_File_iread_at_all 104
#define event_MPI_File_iread_shared 105
#define event_MPI_File_iwrite 106
#define event_MPI_File_iwrite_all 107
#define event_MPI_File_iwrite_at 108
#define event_MPI_File_iwrite_at_all 109
#define event_MPI_File_iwrite_shared 110
#define event_MPI_File_open 111
#define event_MPI_File_preallocate 112
#define event_MPI_File_read 113
#define event_MPI_File_read_all 114
#define event_MPI_File_read_all_begin 115
#define event_MPI_File_read_all_end 116
#define event_MPI_File_read_at 117
#define event_MPI_File_read_at_all 118
#define event_MPI_File_read_at_all_begin 119
#define event_MPI_File_read_at_all_end 120
#define event_MPI_File_read_ordered 121
#define event_MPI_File_read_ordered_begin 122
#define event_MPI_File_read_ordered_end 123
#define event_MPI_File_read_shared 124
#define event_MPI_File_seek 125
#define event_MPI_File_seek_shared 126
#define event_MPI_File_set_atomicity 127
#define event_MPI_File_set_errhandler 128
#define event_MPI_File_set_info 129
#define event_MPI_File_set_size 130
#define event_MPI_File_set_view 131
#define event_MPI_File_sync 132
#define event_MPI_File_write 133
#define event_MPI_File_write_all 134
#define event_MPI_File_write_all_begin 135
#define event_MPI_File_write_all_end 136
#define event_MPI_File_write_at 137
#define event_MPI_File_write_at_all 138
#define event_MPI_File_write_at_all_begin 139
#define event_MPI_File_write_at_all_end 140
#define event_MPI_File_write_ordered 141
#define event_MPI_File_write_ordered_begin 142
#define event_MPI_File_write_ordered_end 143
#define event_MPI_File_write_shared 144
#define event_MPI_Finalized 145
#define event_MPI_Free_mem 146
#define event_MPI_Gather 147
#define event_MPI_Gatherv 148
#define event_MPI_Get 149
#define event_MPI_Get_accumulate 150
#define event_MPI_Get_address 151
#define event_MPI_Get_count 152
#define event_MPI_Get_elements 153
#define event_MPI_Get_elements_x 154
#define event_MPI_Get_library_version 155
#define event_MPI_Get_processor_name 156
#define event_MPI_Get_version 157
#define event_MPI_Graph_create 158
#define event_MPI_Graph_get 159
#define event_MPI_Graph_map 160
#define event_MPI_Graph_neighbors 161
#define event_MPI_Graph_neighbors_count 162
#define event_MPI_Graphdims_get 163
#define event_MPI_Grequest_complete 164
#define event_MPI_Grequest_start 165
#define event_MPI_Group_compare 166
#define event_MPI_Group_difference 167
#define event_MPI_Group_excl 168
#define event_MPI_Group_free 169
#define event_MPI_Group_incl 170
#define event_MPI_Group_intersection 171
#define event_MPI_Group_range_excl 172
#define event_MPI_Group_range_incl 173
#define event_MPI_Group_rank 174
#define event_MPI_Group_size 175
#define event_MPI_Group_translate_ranks 176
#define event_MPI_Group_union 177
#define event_MPI_Iallgather 178
#define event_MPI_Iallgatherv 179
#define event_MPI_Iallreduce 180
#define event_MPI_Ialltoall 181
#define event_MPI_Ialltoallv 182
#define event_MPI_Ialltoallw 183
#define event_MPI_Ibarrier 184
#define event_MPI_Ibcast 185
#define event_MPI_Ibsend 186
#define event_MPI_Iexscan 187
#define event_MPI_Igather 188
#define event_MPI_Igatherv 189
#define event_MPI_Improbe 190
#define event_MPI_Imrecv 191
#define event_MPI_Ineighbor_allgather 192
#define event_MPI_Ineighbor_allgatherv 193
#define event_MPI_Ineighbor_alltoall 194
#define event_MPI_Ineighbor_alltoallv 195
#define event_MPI_Ineighbor_alltoallw 196
#define event_MPI_Info_create 197
#define event_MPI_Info_delete 198
#define event_MPI_Info_dup 199
#define event_MPI_Info_free 200
#define event_MPI_Info_get 201
#define event_MPI_Info_get_nkeys 202
#define event_MPI_Info_get_nthkey 203
#define event_MPI_Info_get_valuelen 204
#define event_MPI_Info_set 205
#define event_MPI_Intercomm_create 206
#define event_MPI_Intercomm_merge 207
#define event_MPI_Iprobe 208
#define event_MPI_Ireduce 209
#define event_MPI_Ireduce_scatter 210
#define event_MPI_Ireduce_scatter_block 211
#define event_MPI_Irsend 212
#define event_MPI_Is_thread_main 213
#define event_MPI_Iscan 214
#define event_MPI_Iscatter 215
#define event_MPI_Iscatterv 216
#define event_MPI_Isend 217
#define event_MPI_Issend 218
#define event_MPI_Keyval_create 219
#define event_MPI_Keyval_free 220
#define event_MPI_Lookup_name 221
#define event_MPI_Mprobe 222
#define event_MPI_Mrecv 223
#define event_MPI_Neighbor_allgather 224
#define event_MPI_Neighbor_allgatherv 225
#define event_MPI_Neighbor_alltoall 226
#define event_MPI_Neighbor_alltoallv 227
#define event_MPI_Neighbor_alltoallw 228
#define event_MPI_Op_commutative 229
#define event_MPI_Op_create 230
#define event_MPI_Op_free 231
#define event_MPI_Open_port 232
#define event_MPI_Pack 233
#define event_MPI_Pack_external 234
#define event_MPI_Pack_external_size 235
#define event_MPI_Pack_size 236
#define event_MPI_Pcontrol 237
#define event_MPI_Probe 238
#define event_MPI_Publish_name 239
#define event_MPI_Put 240
#define event_MPI_Query_thread 241
#define event_MPI_Raccumulate 242
#define event_MPI_Recv_init 243
#define event_MPI_Reduce 244
#define event_MPI_Reduce_local 245
#define event_MPI_Reduce_scatter 246
#define event_MPI_Reduce_scatter_block 247
#define event_MPI_Register_datarep 248
#define event_MPI_Request_free 249
#define event_MPI_Request_get_status 250
#define event_MPI_Rget 251
#define event_MPI_Rget_accumulate 252
#define event_MPI_Rput 253
#define event_MPI_Rsend 254
#define event_MPI_Rsend_init 255
#define event_MPI_Scan 256
#define event_MPI_Scatter 257
#define event_MPI_Scatterv 258
#define event_MPI_Send_init 259
#define event_MPI_Sendrecv 260
#define event_MPI_Sendrecv_replace 261
#define event_MPI_Ssend 262
#define event_MPI_Ssend_init 263
#define event_MPI_Start 264
#define event_MPI_Startall 265
#define event_MPI_Status_set_cancelled 266
#define event_MPI_Status_set_elements 267
#define event_MPI_Status_set_elements_x 268
#define event_MPI_Test 269
#define event_MPI_Test_cancelled 270
#define event_MPI_Testall 271
#define event_MPI_Testany 272
#define event_MPI_Testsome 273
#define event_MPI_Topo_test 274
#define event_MPI_Type_commit 275
#define event_MPI_Type_contiguous 276
#define event_MPI_Type_create_darray 277
#define event_MPI_Type_create_f90_complex 278
#define event_MPI_Type_create_f90_integer 279
#define event_MPI_Type_create_f90_real 280
#define event_MPI_Type_create_hindexed 281
#define event_MPI_Type_create_hindexed_block 282
#define event_MPI_Type_create_hvector 283
#define event_MPI_Type_create_indexed_block 284
#define event_MPI_Type_create_keyval 285
#define event_MPI_Type_create_resized 286
#define event_MPI_Type_create_struct 287
#define event_MPI_Type_create_subarray 288
#define event_MPI_Type_delete_attr 289
#define event_MPI_Type_dup 290
#define event_MPI_Type_extent 291
#define event_MPI_Type_free 292
#define event_MPI_Type_free_keyval 293
#define event_MPI_Type_get_attr 294
#define event_MPI_Type_get_contents 295
#define event_MPI_Type_get_envelope 296
#define event_MPI_Type_get_extent 297
#define event_MPI_Type_get_extent_x 298
#define event_MPI_Type_get_name 299
#define event_MPI_Type_get_true_extent 300
#define event_MPI_Type_get_true_extent_x 301
#define event_MPI_Type_hindexed 302
#define event_MPI_Type_hvector 303
#define event_MPI_Type_indexed 304
#define event_MPI_Type_lb 305
#define event_MPI_Type_match_size 306
#define event_MPI_Type_set_attr 307
#define event_MPI_Type_set_name 308
#define event_MPI_Type_size 309
#define event_MPI_Type_size_x 310
#define event_MPI_Type_struct 311
#define event_MPI_Type_ub 312
#define event_MPI_Type_vector 313
#define event_MPI_Unpack 314
#define event_MPI_Unpack_external 315
#define event_MPI_Unpublish_name 316
#define event_MPI_Wait 317
#define event_MPI_Waitall 318
#define event_MPI_Waitany 319
#define event_MPI_Waitsome 320
#define event_MPI_Win_allocate 321
#define event_MPI_Win_allocate_shared 322
#define event_MPI_Win_attach 323
#define event_MPI_Win_call_errhandler 324
#define event_MPI_Win_complete 325
#define event_MPI_Win_create 326
#define event_MPI_Win_create_dynamic 327
#define event_MPI_Win_create_errhandler 328
#define event_MPI_Win_create_keyval 329
#define event_MPI_Win_delete_attr 330
#define event_MPI_Win_detach 331
#define event_MPI_Win_fence 332
#define event_MPI_Win_flush 333
#define event_MPI_Win_flush_all 334
#define event_MPI_Win_flush_local 335
#define event_MPI_Win_flush_local_all 336
#define event_MPI_Win_free 337
#define event_MPI_Win_free_keyval 338
#define event_MPI_Win_get_attr 339
#define event_MPI_Win_get_errhandler 340
#define event_MPI_Win_get_group 341
#define event_MPI_Win_get_info 342
#define event_MPI_Win_get_name 343
#define event_MPI_Win_lock 344
#define event_MPI_Win_lock_all 345
#define event_MPI_Win_post 346
#define event_MPI_Win_set_attr 347
#define event_MPI_Win_set_errhandler 348
#define event_MPI_Win_set_info 349
#define event_MPI_Win_set_name 350
#define event_MPI_Win_shared_query 351
#define event_MPI_Win_start 352
#define event_MPI_Win_sync 353
#define event_MPI_Win_test 354
#define event_MPI_Win_unlock 355
#define event_MPI_Win_unlock_all 356
#define event_MPI_Win_wait 357
#define event_MPI_Wtick 358
#define event_MPI_Wtime 359
#define event_MPI_Init_thread 360
#define event_Memory_Malloc 361
#define event_Memory_Calloc 362
#define event_Memory_Realloc 363
#define event_Memory_Free 364
#define __RECORD_MAP_IMPL \
  case 0: return std::string("MPI_Init");\
  case 1: return std::string("MPI_Finalize");\
  case 2: return std::string("MPI_Send");\
  case 3: return std::string("MPI_Recv");\
  case 4: return std::string("MPI_Irecv");\
  case 5: return std::string("MPI_Abort");\
  case 6: return std::string("MPI_Accumulate");\
  case 7: return std::string("MPI_Add_error_class");\
  case 8: return std::string("MPI_Add_error_code");\
  case 9: return std::string("MPI_Add_error_string");\
  case 10: return std::string("MPI_Address");\
  case 11: return std::string("MPI_Aint_add");\
  case 12: return std::string("MPI_Aint_diff");\
  case 13: return std::string("MPI_Allgather");\
  case 14: return std::string("MPI_Allgatherv");\
  case 15: return std::string("MPI_Alloc_mem");\
  case 16: return std::string("MPI_Allreduce");\
  case 17: return std::string("MPI_Alltoall");\
  case 18: return std::string("MPI_Alltoallv");\
  case 19: return std::string("MPI_Alltoallw");\
  case 20: return std::string("MPI_Attr_delete");\
  case 21: return std::string("MPI_Attr_get");\
  case 22: return std::string("MPI_Attr_put");\
  case 23: return std::string("MPI_Barrier");\
  case 24: return std::string("MPI_Bcast");\
  case 25: return std::string("MPI_Bsend");\
  case 26: return std::string("MPI_Bsend_init");\
  case 27: return std::string("MPI_Buffer_attach");\
  case 28: return std::string("MPI_Buffer_detach");\
  case 29: return std::string("MPI_Cancel");\
  case 30: return std::string("MPI_Cart_coords");\
  case 31: return std::string("MPI_Cart_create");\
  case 32: return std::string("MPI_Cart_get");\
  case 33: return std::string("MPI_Cart_map");\
  case 34: return std::string("MPI_Cart_rank");\
  case 35: return std::string("MPI_Cart_shift");\
  case 36: return std::string("MPI_Cart_sub");\
  case 37: return std::string("MPI_Cartdim_get");\
  case 38: return std::string("MPI_Close_port");\
  case 39: return std::string("MPI_Comm_accept");\
  case 40: return std::string("MPI_Comm_call_errhandler");\
  case 41: return std::string("MPI_Comm_compare");\
  case 42: return std::string("MPI_Comm_connect");\
  case 43: return std::string("MPI_Comm_create");\
  case 44: return std::string("MPI_Comm_create_errhandler");\
  case 45: return std::string("MPI_Comm_create_group");\
  case 46: return std::string("MPI_Comm_create_keyval");\
  case 47: return std::string("MPI_Comm_delete_attr");\
  case 48: return std::string("MPI_Comm_disconnect");\
  case 49: return std::string("MPI_Comm_dup");\
  case 50: return std::string("MPI_Comm_dup_with_info");\
  case 51: return std::string("MPI_Comm_free");\
  case 52: return std::string("MPI_Comm_free_keyval");\
  case 53: return std::string("MPI_Comm_get_attr");\
  case 54: return std::string("MPI_Comm_get_errhandler");\
  case 55: return std::string("MPI_Comm_get_info");\
  case 56: return std::string("MPI_Comm_get_name");\
  case 57: return std::string("MPI_Comm_get_parent");\
  case 58: return std::string("MPI_Comm_group");\
  case 59: return std::string("MPI_Comm_idup");\
  case 60: return std::string("MPI_Comm_join");\
  case 61: return std::string("MPI_Comm_rank");\
  case 62: return std::string("MPI_Comm_remote_group");\
  case 63: return std::string("MPI_Comm_remote_size");\
  case 64: return std::string("MPI_Comm_set_attr");\
  case 65: return std::string("MPI_Comm_set_errhandler");\
  case 66: return std::string("MPI_Comm_set_info");\
  case 67: return std::string("MPI_Comm_set_name");\
  case 68: return std::string("MPI_Comm_size");\
  case 69: return std::string("MPI_Comm_split");\
  case 70: return std::string("MPI_Comm_split_type");\
  case 71: return std::string("MPI_Comm_test_inter");\
  case 72: return std::string("MPI_Compare_and_swap");\
  case 73: return std::string("MPI_Dims_create");\
  case 74: return std::string("MPI_Dist_graph_create");\
  case 75: return std::string("MPI_Dist_graph_create_adjacent");\
  case 76: return std::string("MPI_Dist_graph_neighbors");\
  case 77: return std::string("MPI_Dist_graph_neighbors_count");\
  case 78: return std::string("MPI_Errhandler_create");\
  case 79: return std::string("MPI_Errhandler_free");\
  case 80: return std::string("MPI_Errhandler_get");\
  case 81: return std::string("MPI_Errhandler_set");\
  case 82: return std::string("MPI_Error_class");\
  case 83: return std::string("MPI_Error_string");\
  case 84: return std::string("MPI_Exscan");\
  case 85: return std::string("MPI_Fetch_and_op");\
  case 86: return std::string("MPI_File_call_errhandler");\
  case 87: return std::string("MPI_File_close");\
  case 88: return std::string("MPI_File_create_errhandler");\
  case 89: return std::string("MPI_File_delete");\
  case 90: return std::string("MPI_File_get_amode");\
  case 91: return std::string("MPI_File_get_atomicity");\
  case 92: return std::string("MPI_File_get_byte_offset");\
  case 93: return std::string("MPI_File_get_errhandler");\
  case 94: return std::string("MPI_File_get_group");\
  case 95: return std::string("MPI_File_get_info");\
  case 96: return std::string("MPI_File_get_position");\
  case 97: return std::string("MPI_File_get_position_shared");\
  case 98: return std::string("MPI_File_get_size");\
  case 99: return std::string("MPI_File_get_type_extent");\
  case 100: return std::string("MPI_File_get_view");\
  case 101: return std::string("MPI_File_iread");\
  case 102: return std::string("MPI_File_iread_all");\
  case 103: return std::string("MPI_File_iread_at");\
  case 104: return std::string("MPI_File_iread_at_all");\
  case 105: return std::string("MPI_File_iread_shared");\
  case 106: return std::string("MPI_File_iwrite");\
  case 107: return std::string("MPI_File_iwrite_all");\
  case 108: return std::string("MPI_File_iwrite_at");\
  case 109: return std::string("MPI_File_iwrite_at_all");\
  case 110: return std::string("MPI_File_iwrite_shared");\
  case 111: return std::string("MPI_File_open");\
  case 112: return std::string("MPI_File_preallocate");\
  case 113: return std::string("MPI_File_read");\
  case 114: return std::string("MPI_File_read_all");\
  case 115: return std::string("MPI_File_read_all_begin");\
  case 116: return std::string("MPI_File_read_all_end");\
  case 117: return std::string("MPI_File_read_at");\
  case 118: return std::string("MPI_File_read_at_all");\
  case 119: return std::string("MPI_File_read_at_all_begin");\
  case 120: return std::string("MPI_File_read_at_all_end");\
  case 121: return std::string("MPI_File_read_ordered");\
  case 122: return std::string("MPI_File_read_ordered_begin");\
  case 123: return std::string("MPI_File_read_ordered_end");\
  case 124: return std::string("MPI_File_read_shared");\
  case 125: return std::string("MPI_File_seek");\
  case 126: return std::string("MPI_File_seek_shared");\
  case 127: return std::string("MPI_File_set_atomicity");\
  case 128: return std::string("MPI_File_set_errhandler");\
  case 129: return std::string("MPI_File_set_info");\
  case 130: return std::string("MPI_File_set_size");\
  case 131: return std::string("MPI_File_set_view");\
  case 132: return std::string("MPI_File_sync");\
  case 133: return std::string("MPI_File_write");\
  case 134: return std::string("MPI_File_write_all");\
  case 135: return std::string("MPI_File_write_all_begin");\
  case 136: return std::string("MPI_File_write_all_end");\
  case 137: return std::string("MPI_File_write_at");\
  case 138: return std::string("MPI_File_write_at_all");\
  case 139: return std::string("MPI_File_write_at_all_begin");\
  case 140: return std::string("MPI_File_write_at_all_end");\
  case 141: return std::string("MPI_File_write_ordered");\
  case 142: return std::string("MPI_File_write_ordered_begin");\
  case 143: return std::string("MPI_File_write_ordered_end");\
  case 144: return std::string("MPI_File_write_shared");\
  case 145: return std::string("MPI_Finalized");\
  case 146: return std::string("MPI_Free_mem");\
  case 147: return std::string("MPI_Gather");\
  case 148: return std::string("MPI_Gatherv");\
  case 149: return std::string("MPI_Get");\
  case 150: return std::string("MPI_Get_accumulate");\
  case 151: return std::string("MPI_Get_address");\
  case 152: return std::string("MPI_Get_count");\
  case 153: return std::string("MPI_Get_elements");\
  case 154: return std::string("MPI_Get_elements_x");\
  case 155: return std::string("MPI_Get_library_version");\
  case 156: return std::string("MPI_Get_processor_name");\
  case 157: return std::string("MPI_Get_version");\
  case 158: return std::string("MPI_Graph_create");\
  case 159: return std::string("MPI_Graph_get");\
  case 160: return std::string("MPI_Graph_map");\
  case 161: return std::string("MPI_Graph_neighbors");\
  case 162: return std::string("MPI_Graph_neighbors_count");\
  case 163: return std::string("MPI_Graphdims_get");\
  case 164: return std::string("MPI_Grequest_complete");\
  case 165: return std::string("MPI_Grequest_start");\
  case 166: return std::string("MPI_Group_compare");\
  case 167: return std::string("MPI_Group_difference");\
  case 168: return std::string("MPI_Group_excl");\
  case 169: return std::string("MPI_Group_free");\
  case 170: return std::string("MPI_Group_incl");\
  case 171: return std::string("MPI_Group_intersection");\
  case 172: return std::string("MPI_Group_range_excl");\
  case 173: return std::string("MPI_Group_range_incl");\
  case 174: return std::string("MPI_Group_rank");\
  case 175: return std::string("MPI_Group_size");\
  case 176: return std::string("MPI_Group_translate_ranks");\
  case 177: return std::string("MPI_Group_union");\
  case 178: return std::string("MPI_Iallgather");\
  case 179: return std::string("MPI_Iallgatherv");\
  case 180: return std::string("MPI_Iallreduce");\
  case 181: return std::string("MPI_Ialltoall");\
  case 182: return std::string("MPI_Ialltoallv");\
  case 183: return std::string("MPI_Ialltoallw");\
  case 184: return std::string("MPI_Ibarrier");\
  case 185: return std::string("MPI_Ibcast");\
  case 186: return std::string("MPI_Ibsend");\
  case 187: return std::string("MPI_Iexscan");\
  case 188: return std::string("MPI_Igather");\
  case 189: return std::string("MPI_Igatherv");\
  case 190: return std::string("MPI_Improbe");\
  case 191: return std::string("MPI_Imrecv");\
  case 192: return std::string("MPI_Ineighbor_allgather");\
  case 193: return std::string("MPI_Ineighbor_allgatherv");\
  case 194: return std::string("MPI_Ineighbor_alltoall");\
  case 195: return std::string("MPI_Ineighbor_alltoallv");\
  case 196: return std::string("MPI_Ineighbor_alltoallw");\
  case 197: return std::string("MPI_Info_create");\
  case 198: return std::string("MPI_Info_delete");\
  case 199: return std::string("MPI_Info_dup");\
  case 200: return std::string("MPI_Info_free");\
  case 201: return std::string("MPI_Info_get");\
  case 202: return std::string("MPI_Info_get_nkeys");\
  case 203: return std::string("MPI_Info_get_nthkey");\
  case 204: return std::string("MPI_Info_get_valuelen");\
  case 205: return std::string("MPI_Info_set");\
  case 206: return std::string("MPI_Intercomm_create");\
  case 207: return std::string("MPI_Intercomm_merge");\
  case 208: return std::string("MPI_Iprobe");\
  case 209: return std::string("MPI_Ireduce");\
  case 210: return std::string("MPI_Ireduce_scatter");\
  case 211: return std::string("MPI_Ireduce_scatter_block");\
  case 212: return std::string("MPI_Irsend");\
  case 213: return std::string("MPI_Is_thread_main");\
  case 214: return std::string("MPI_Iscan");\
  case 215: return std::string("MPI_Iscatter");\
  case 216: return std::string("MPI_Iscatterv");\
  case 217: return std::string("MPI_Isend");\
  case 218: return std::string("MPI_Issend");\
  case 219: return std::string("MPI_Keyval_create");\
  case 220: return std::string("MPI_Keyval_free");\
  case 221: return std::string("MPI_Lookup_name");\
  case 222: return std::string("MPI_Mprobe");\
  case 223: return std::string("MPI_Mrecv");\
  case 224: return std::string("MPI_Neighbor_allgather");\
  case 225: return std::string("MPI_Neighbor_allgatherv");\
  case 226: return std::string("MPI_Neighbor_alltoall");\
  case 227: return std::string("MPI_Neighbor_alltoallv");\
  case 228: return std::string("MPI_Neighbor_alltoallw");\
  case 229: return std::string("MPI_Op_commutative");\
  case 230: return std::string("MPI_Op_create");\
  case 231: return std::string("MPI_Op_free");\
  case 232: return std::string("MPI_Open_port");\
  case 233: return std::string("MPI_Pack");\
  case 234: return std::string("MPI_Pack_external");\
  case 235: return std::string("MPI_Pack_external_size");\
  case 236: return std::string("MPI_Pack_size");\
  case 237: return std::string("MPI_Pcontrol");\
  case 238: return std::string("MPI_Probe");\
  case 239: return std::string("MPI_Publish_name");\
  case 240: return std::string("MPI_Put");\
  case 241: return std::string("MPI_Query_thread");\
  case 242: return std::string("MPI_Raccumulate");\
  case 243: return std::string("MPI_Recv_init");\
  case 244: return std::string("MPI_Reduce");\
  case 245: return std::string("MPI_Reduce_local");\
  case 246: return std::string("MPI_Reduce_scatter");\
  case 247: return std::string("MPI_Reduce_scatter_block");\
  case 248: return std::string("MPI_Register_datarep");\
  case 249: return std::string("MPI_Request_free");\
  case 250: return std::string("MPI_Request_get_status");\
  case 251: return std::string("MPI_Rget");\
  case 252: return std::string("MPI_Rget_accumulate");\
  case 253: return std::string("MPI_Rput");\
  case 254: return std::string("MPI_Rsend");\
  case 255: return std::string("MPI_Rsend_init");\
  case 256: return std::string("MPI_Scan");\
  case 257: return std::string("MPI_Scatter");\
  case 258: return std::string("MPI_Scatterv");\
  case 259: return std::string("MPI_Send_init");\
  case 260: return std::string("MPI_Sendrecv");\
  case 261: return std::string("MPI_Sendrecv_replace");\
  case 262: return std::string("MPI_Ssend");\
  case 263: return std::string("MPI_Ssend_init");\
  case 264: return std::string("MPI_Start");\
  case 265: return std::string("MPI_Startall");\
  case 266: return std::string("MPI_Status_set_cancelled");\
  case 267: return std::string("MPI_Status_set_elements");\
  case 268: return std::string("MPI_Status_set_elements_x");\
  case 269: return std::string("MPI_Test");\
  case 270: return std::string("MPI_Test_cancelled");\
  case 271: return std::string("MPI_Testall");\
  case 272: return std::string("MPI_Testany");\
  case 273: return std::string("MPI_Testsome");\
  case 274: return std::string("MPI_Topo_test");\
  case 275: return std::string("MPI_Type_commit");\
  case 276: return std::string("MPI_Type_contiguous");\
  case 277: return std::string("MPI_Type_create_darray");\
  case 278: return std::string("MPI_Type_create_f90_complex");\
  case 279: return std::string("MPI_Type_create_f90_integer");\
  case 280: return std::string("MPI_Type_create_f90_real");\
  case 281: return std::string("MPI_Type_create_hindexed");\
  case 282: return std::string("MPI_Type_create_hindexed_block");\
  case 283: return std::string("MPI_Type_create_hvector");\
  case 284: return std::string("MPI_Type_create_indexed_block");\
  case 285: return std::string("MPI_Type_create_keyval");\
  case 286: return std::string("MPI_Type_create_resized");\
  case 287: return std::string("MPI_Type_create_struct");\
  case 288: return std::string("MPI_Type_create_subarray");\
  case 289: return std::string("MPI_Type_delete_attr");\
  case 290: return std::string("MPI_Type_dup");\
  case 291: return std::string("MPI_Type_extent");\
  case 292: return std::string("MPI_Type_free");\
  case 293: return std::string("MPI_Type_free_keyval");\
  case 294: return std::string("MPI_Type_get_attr");\
  case 295: return std::string("MPI_Type_get_contents");\
  case 296: return std::string("MPI_Type_get_envelope");\
  case 297: return std::string("MPI_Type_get_extent");\
  case 298: return std::string("MPI_Type_get_extent_x");\
  case 299: return std::string("MPI_Type_get_name");\
  case 300: return std::string("MPI_Type_get_true_extent");\
  case 301: return std::string("MPI_Type_get_true_extent_x");\
  case 302: return std::string("MPI_Type_hindexed");\
  case 303: return std::string("MPI_Type_hvector");\
  case 304: return std::string("MPI_Type_indexed");\
  case 305: return std::string("MPI_Type_lb");\
  case 306: return std::string("MPI_Type_match_size");\
  case 307: return std::string("MPI_Type_set_attr");\
  case 308: return std::string("MPI_Type_set_name");\
  case 309: return std::string("MPI_Type_size");\
  case 310: return std::string("MPI_Type_size_x");\
  case 311: return std::string("MPI_Type_struct");\
  case 312: return std::string("MPI_Type_ub");\
  case 313: return std::string("MPI_Type_vector");\
  case 314: return std::string("MPI_Unpack");\
  case 315: return std::string("MPI_Unpack_external");\
  case 316: return std::string("MPI_Unpublish_name");\
  case 317: return std::string("MPI_Wait");\
  case 318: return std::string("MPI_Waitall");\
  case 319: return std::string("MPI_Waitany");\
  case 320: return std::string("MPI_Waitsome");\
  case 321: return std::string("MPI_Win_allocate");\
  case 322: return std::string("MPI_Win_allocate_shared");\
  case 323: return std::string("MPI_Win_attach");\
  case 324: return std::string("MPI_Win_call_errhandler");\
  case 325: return std::string("MPI_Win_complete");\
  case 326: return std::string("MPI_Win_create");\
  case 327: return std::string("MPI_Win_create_dynamic");\
  case 328: return std::string("MPI_Win_create_errhandler");\
  case 329: return std::string("MPI_Win_create_keyval");\
  case 330: return std::string("MPI_Win_delete_attr");\
  case 331: return std::string("MPI_Win_detach");\
  case 332: return std::string("MPI_Win_fence");\
  case 333: return std::string("MPI_Win_flush");\
  case 334: return std::string("MPI_Win_flush_all");\
  case 335: return std::string("MPI_Win_flush_local");\
  case 336: return std::string("MPI_Win_flush_local_all");\
  case 337: return std::string("MPI_Win_free");\
  case 338: return std::string("MPI_Win_free_keyval");\
  case 339: return std::string("MPI_Win_get_attr");\
  case 340: return std::string("MPI_Win_get_errhandler");\
  case 341: return std::string("MPI_Win_get_group");\
  case 342: return std::string("MPI_Win_get_info");\
  case 343: return std::string("MPI_Win_get_name");\
  case 344: return std::string("MPI_Win_lock");\
  case 345: return std::string("MPI_Win_lock_all");\
  case 346: return std::string("MPI_Win_post");\
  case 347: return std::string("MPI_Win_set_attr");\
  case 348: return std::string("MPI_Win_set_errhandler");\
  case 349: return std::string("MPI_Win_set_info");\
  case 350: return std::string("MPI_Win_set_name");\
  case 351: return std::string("MPI_Win_shared_query");\
  case 352: return std::string("MPI_Win_start");\
  case 353: return std::string("MPI_Win_sync");\
  case 354: return std::string("MPI_Win_test");\
  case 355: return std::string("MPI_Win_unlock");\
  case 356: return std::string("MPI_Win_unlock_all");\
  case 357: return std::string("MPI_Win_wait");\
  case 358: return std::string("MPI_Wtick");\
  case 359: return std::string("MPI_Wtime");\
  case 360: return std::string("MPI_Init_thread");\
  case 361: return std::string("Memory_Malloc");\
  case 362: return std::string("Memory_Calloc");\
  case 363: return std::string("Memory_Realloc");\
  case 364: return std::string("Memory_Free");
enum class event
{
MPI_Init = 0,
MPI_Finalize = 1,
MPI_Send = 2,
MPI_Recv = 3,
MPI_Irecv = 4,
MPI_Abort = 5,
MPI_Accumulate = 6,
MPI_Add_error_class = 7,
MPI_Add_error_code = 8,
MPI_Add_error_string = 9,
MPI_Address = 10,
MPI_Aint_add = 11,
MPI_Aint_diff = 12,
MPI_Allgather = 13,
MPI_Allgatherv = 14,
MPI_Alloc_mem = 15,
MPI_Allreduce = 16,
MPI_Alltoall = 17,
MPI_Alltoallv = 18,
MPI_Alltoallw = 19,
MPI_Attr_delete = 20,
MPI_Attr_get = 21,
MPI_Attr_put = 22,
MPI_Barrier = 23,
MPI_Bcast = 24,
MPI_Bsend = 25,
MPI_Bsend_init = 26,
MPI_Buffer_attach = 27,
MPI_Buffer_detach = 28,
MPI_Cancel = 29,
MPI_Cart_coords = 30,
MPI_Cart_create = 31,
MPI_Cart_get = 32,
MPI_Cart_map = 33,
MPI_Cart_rank = 34,
MPI_Cart_shift = 35,
MPI_Cart_sub = 36,
MPI_Cartdim_get = 37,
MPI_Close_port = 38,
MPI_Comm_accept = 39,
MPI_Comm_call_errhandler = 40,
MPI_Comm_compare = 41,
MPI_Comm_connect = 42,
MPI_Comm_create = 43,
MPI_Comm_create_errhandler = 44,
MPI_Comm_create_group = 45,
MPI_Comm_create_keyval = 46,
MPI_Comm_delete_attr = 47,
MPI_Comm_disconnect = 48,
MPI_Comm_dup = 49,
MPI_Comm_dup_with_info = 50,
MPI_Comm_free = 51,
MPI_Comm_free_keyval = 52,
MPI_Comm_get_attr = 53,
MPI_Comm_get_errhandler = 54,
MPI_Comm_get_info = 55,
MPI_Comm_get_name = 56,
MPI_Comm_get_parent = 57,
MPI_Comm_group = 58,
MPI_Comm_idup = 59,
MPI_Comm_join = 60,
MPI_Comm_rank = 61,
MPI_Comm_remote_group = 62,
MPI_Comm_remote_size = 63,
MPI_Comm_set_attr = 64,
MPI_Comm_set_errhandler = 65,
MPI_Comm_set_info = 66,
MPI_Comm_set_name = 67,
MPI_Comm_size = 68,
MPI_Comm_split = 69,
MPI_Comm_split_type = 70,
MPI_Comm_test_inter = 71,
MPI_Compare_and_swap = 72,
MPI_Dims_create = 73,
MPI_Dist_graph_create = 74,
MPI_Dist_graph_create_adjacent = 75,
MPI_Dist_graph_neighbors = 76,
MPI_Dist_graph_neighbors_count = 77,
MPI_Errhandler_create = 78,
MPI_Errhandler_free = 79,
MPI_Errhandler_get = 80,
MPI_Errhandler_set = 81,
MPI_Error_class = 82,
MPI_Error_string = 83,
MPI_Exscan = 84,
MPI_Fetch_and_op = 85,
MPI_File_call_errhandler = 86,
MPI_File_close = 87,
MPI_File_create_errhandler = 88,
MPI_File_delete = 89,
MPI_File_get_amode = 90,
MPI_File_get_atomicity = 91,
MPI_File_get_byte_offset = 92,
MPI_File_get_errhandler = 93,
MPI_File_get_group = 94,
MPI_File_get_info = 95,
MPI_File_get_position = 96,
MPI_File_get_position_shared = 97,
MPI_File_get_size = 98,
MPI_File_get_type_extent = 99,
MPI_File_get_view = 100,
MPI_File_iread = 101,
MPI_File_iread_all = 102,
MPI_File_iread_at = 103,
MPI_File_iread_at_all = 104,
MPI_File_iread_shared = 105,
MPI_File_iwrite = 106,
MPI_File_iwrite_all = 107,
MPI_File_iwrite_at = 108,
MPI_File_iwrite_at_all = 109,
MPI_File_iwrite_shared = 110,
MPI_File_open = 111,
MPI_File_preallocate = 112,
MPI_File_read = 113,
MPI_File_read_all = 114,
MPI_File_read_all_begin = 115,
MPI_File_read_all_end = 116,
MPI_File_read_at = 117,
MPI_File_read_at_all = 118,
MPI_File_read_at_all_begin = 119,
MPI_File_read_at_all_end = 120,
MPI_File_read_ordered = 121,
MPI_File_read_ordered_begin = 122,
MPI_File_read_ordered_end = 123,
MPI_File_read_shared = 124,
MPI_File_seek = 125,
MPI_File_seek_shared = 126,
MPI_File_set_atomicity = 127,
MPI_File_set_errhandler = 128,
MPI_File_set_info = 129,
MPI_File_set_size = 130,
MPI_File_set_view = 131,
MPI_File_sync = 132,
MPI_File_write = 133,
MPI_File_write_all = 134,
MPI_File_write_all_begin = 135,
MPI_File_write_all_end = 136,
MPI_File_write_at = 137,
MPI_File_write_at_all = 138,
MPI_File_write_at_all_begin = 139,
MPI_File_write_at_all_end = 140,
MPI_File_write_ordered = 141,
MPI_File_write_ordered_begin = 142,
MPI_File_write_ordered_end = 143,
MPI_File_write_shared = 144,
MPI_Finalized = 145,
MPI_Free_mem = 146,
MPI_Gather = 147,
MPI_Gatherv = 148,
MPI_Get = 149,
MPI_Get_accumulate = 150,
MPI_Get_address = 151,
MPI_Get_count = 152,
MPI_Get_elements = 153,
MPI_Get_elements_x = 154,
MPI_Get_library_version = 155,
MPI_Get_processor_name = 156,
MPI_Get_version = 157,
MPI_Graph_create = 158,
MPI_Graph_get = 159,
MPI_Graph_map = 160,
MPI_Graph_neighbors = 161,
MPI_Graph_neighbors_count = 162,
MPI_Graphdims_get = 163,
MPI_Grequest_complete = 164,
MPI_Grequest_start = 165,
MPI_Group_compare = 166,
MPI_Group_difference = 167,
MPI_Group_excl = 168,
MPI_Group_free = 169,
MPI_Group_incl = 170,
MPI_Group_intersection = 171,
MPI_Group_range_excl = 172,
MPI_Group_range_incl = 173,
MPI_Group_rank = 174,
MPI_Group_size = 175,
MPI_Group_translate_ranks = 176,
MPI_Group_union = 177,
MPI_Iallgather = 178,
MPI_Iallgatherv = 179,
MPI_Iallreduce = 180,
MPI_Ialltoall = 181,
MPI_Ialltoallv = 182,
MPI_Ialltoallw = 183,
MPI_Ibarrier = 184,
MPI_Ibcast = 185,
MPI_Ibsend = 186,
MPI_Iexscan = 187,
MPI_Igather = 188,
MPI_Igatherv = 189,
MPI_Improbe = 190,
MPI_Imrecv = 191,
MPI_Ineighbor_allgather = 192,
MPI_Ineighbor_allgatherv = 193,
MPI_Ineighbor_alltoall = 194,
MPI_Ineighbor_alltoallv = 195,
MPI_Ineighbor_alltoallw = 196,
MPI_Info_create = 197,
MPI_Info_delete = 198,
MPI_Info_dup = 199,
MPI_Info_free = 200,
MPI_Info_get = 201,
MPI_Info_get_nkeys = 202,
MPI_Info_get_nthkey = 203,
MPI_Info_get_valuelen = 204,
MPI_Info_set = 205,
MPI_Intercomm_create = 206,
MPI_Intercomm_merge = 207,
MPI_Iprobe = 208,
MPI_Ireduce = 209,
MPI_Ireduce_scatter = 210,
MPI_Ireduce_scatter_block = 211,
MPI_Irsend = 212,
MPI_Is_thread_main = 213,
MPI_Iscan = 214,
MPI_Iscatter = 215,
MPI_Iscatterv = 216,
MPI_Isend = 217,
MPI_Issend = 218,
MPI_Keyval_create = 219,
MPI_Keyval_free = 220,
MPI_Lookup_name = 221,
MPI_Mprobe = 222,
MPI_Mrecv = 223,
MPI_Neighbor_allgather = 224,
MPI_Neighbor_allgatherv = 225,
MPI_Neighbor_alltoall = 226,
MPI_Neighbor_alltoallv = 227,
MPI_Neighbor_alltoallw = 228,
MPI_Op_commutative = 229,
MPI_Op_create = 230,
MPI_Op_free = 231,
MPI_Open_port = 232,
MPI_Pack = 233,
MPI_Pack_external = 234,
MPI_Pack_external_size = 235,
MPI_Pack_size = 236,
MPI_Pcontrol = 237,
MPI_Probe = 238,
MPI_Publish_name = 239,
MPI_Put = 240,
MPI_Query_thread = 241,
MPI_Raccumulate = 242,
MPI_Recv_init = 243,
MPI_Reduce = 244,
MPI_Reduce_local = 245,
MPI_Reduce_scatter = 246,
MPI_Reduce_scatter_block = 247,
MPI_Register_datarep = 248,
MPI_Request_free = 249,
MPI_Request_get_status = 250,
MPI_Rget = 251,
MPI_Rget_accumulate = 252,
MPI_Rput = 253,
MPI_Rsend = 254,
MPI_Rsend_init = 255,
MPI_Scan = 256,
MPI_Scatter = 257,
MPI_Scatterv = 258,
MPI_Send_init = 259,
MPI_Sendrecv = 260,
MPI_Sendrecv_replace = 261,
MPI_Ssend = 262,
MPI_Ssend_init = 263,
MPI_Start = 264,
MPI_Startall = 265,
MPI_Status_set_cancelled = 266,
MPI_Status_set_elements = 267,
MPI_Status_set_elements_x = 268,
MPI_Test = 269,
MPI_Test_cancelled = 270,
MPI_Testall = 271,
MPI_Testany = 272,
MPI_Testsome = 273,
MPI_Topo_test = 274,
MPI_Type_commit = 275,
MPI_Type_contiguous = 276,
MPI_Type_create_darray = 277,
MPI_Type_create_f90_complex = 278,
MPI_Type_create_f90_integer = 279,
MPI_Type_create_f90_real = 280,
MPI_Type_create_hindexed = 281,
MPI_Type_create_hindexed_block = 282,
MPI_Type_create_hvector = 283,
MPI_Type_create_indexed_block = 284,
MPI_Type_create_keyval = 285,
MPI_Type_create_resized = 286,
MPI_Type_create_struct = 287,
MPI_Type_create_subarray = 288,
MPI_Type_delete_attr = 289,
MPI_Type_dup = 290,
MPI_Type_extent = 291,
MPI_Type_free = 292,
MPI_Type_free_keyval = 293,
MPI_Type_get_attr = 294,
MPI_Type_get_contents = 295,
MPI_Type_get_envelope = 296,
MPI_Type_get_extent = 297,
MPI_Type_get_extent_x = 298,
MPI_Type_get_name = 299,
MPI_Type_get_true_extent = 300,
MPI_Type_get_true_extent_x = 301,
MPI_Type_hindexed = 302,
MPI_Type_hvector = 303,
MPI_Type_indexed = 304,
MPI_Type_lb = 305,
MPI_Type_match_size = 306,
MPI_Type_set_attr = 307,
MPI_Type_set_name = 308,
MPI_Type_size = 309,
MPI_Type_size_x = 310,
MPI_Type_struct = 311,
MPI_Type_ub = 312,
MPI_Type_vector = 313,
MPI_Unpack = 314,
MPI_Unpack_external = 315,
MPI_Unpublish_name = 316,
MPI_Wait = 317,
MPI_Waitall = 318,
MPI_Waitany = 319,
MPI_Waitsome = 320,
MPI_Win_allocate = 321,
MPI_Win_allocate_shared = 322,
MPI_Win_attach = 323,
MPI_Win_call_errhandler = 324,
MPI_Win_complete = 325,
MPI_Win_create = 326,
MPI_Win_create_dynamic = 327,
MPI_Win_create_errhandler = 328,
MPI_Win_create_keyval = 329,
MPI_Win_delete_attr = 330,
MPI_Win_detach = 331,
MPI_Win_fence = 332,
MPI_Win_flush = 333,
MPI_Win_flush_all = 334,
MPI_Win_flush_local = 335,
MPI_Win_flush_local_all = 336,
MPI_Win_free = 337,
MPI_Win_free_keyval = 338,
MPI_Win_get_attr = 339,
MPI_Win_get_errhandler = 340,
MPI_Win_get_group = 341,
MPI_Win_get_info = 342,
MPI_Win_get_name = 343,
MPI_Win_lock = 344,
MPI_Win_lock_all = 345,
MPI_Win_post = 346,
MPI_Win_set_attr = 347,
MPI_Win_set_errhandler = 348,
MPI_Win_set_info = 349,
MPI_Win_set_name = 350,
MPI_Win_shared_query = 351,
MPI_Win_start = 352,
MPI_Win_sync = 353,
MPI_Win_test = 354,
MPI_Win_unlock = 355,
MPI_Win_unlock_all = 356,
MPI_Win_wait = 357,
MPI_Wtick = 358,
MPI_Wtime = 359,
MPI_Init_thread = 360,
Memory_Malloc = 361,
Memory_Calloc = 362,
Memory_Realloc = 363,
Memory_Free = 364,
};

#endif