#include "alignment.h"
#include <iostream>
#include "utils/cxxopts.hpp"
#include <filesystem>
#include <stdio.h>

namespace fs = std::filesystem;

std::string input_dir;

void parse(int argc, char *argv[]) {
    cxxopts::Options options("alignment_test", "Align the measured MPI traces with analyzed offset.");
    options.add_options()
        ("h,help", "Print help")
        ("i,input", "Input measurement directory generated by jsirun", cxxopts::value<std::string>())
        ;

    try {
        auto result = options.parse(argc, argv);
        // print help message if configured
        if (result.count("help")) {
            std::cout << options.help() << std::endl;
            exit(1);
        }
        if (result.count("input")>=1) {
            if(result.count("input")>2) {
                std::cout << "Warning: multiple input directory configured. Only use the last one!" << std::endl;
            }
            input_dir = result["input"].as<std::string>();
        } else {
            std::cout << "-i or --input must be specified!" << std::endl;
            exit(1);
        }
        std::cout << "Configured: " << std::endl;
        std::cout << "\t" << "Input: " << input_dir << std::endl;
    } catch (cxxopts::exceptions::exception e) {
        std::cout << "Error: " << e.what() << std::endl;
        std::cout << options.help() << std::endl;
        exit(1);
    }
}

int main(int argc, char* argv[]) {
    parse(argc, argv);
    try {
        RecordReader reader(input_dir.c_str(),DATA_MODEL);
        RecordTraceCollection& traces = reader.get_all_traces();
        RankMetaCollection& metas = reader.get_all_meta_maps();
        TimelineAlignment ta;
        ta.align(traces, metas);
        for (auto it = traces.begin(), ie = traces.end(); it != ie; ++it) {
	    printf("Process %d timeline offset: %lu\n", it->first, it->second->offset);
	}
    } catch (fs::filesystem_error const& e) {
        std::cout << e.what() << std::endl;
        exit(1);
    }
    return 0;
}
