#include <filesystem>
#include <iostream>
#include <fstream>

#include "../timeline/alignment.h"
#include "pbg.hpp"
#include "record/record_reader.h"
#include "utils/cxxopts.hpp"

namespace fs = std::filesystem;

std::string big_input_dir;
std::string small_input_dir;
std::string dump_dir;
std::string output_path;

int top_k = 3;

double anomaly_threshhold = 2.0;
double decay_factor       = 0.5;
double merge_factor       = 0.4;
double time_ratio         = 0.3;
double ins_ratio          = 0.4;
double var_ratio          = 0.3;

void parse(int argc, char* argv[]) {
    cxxopts::Options options(
        "scalability_analysis",
        "Read the measurement directory generated by jsirun and prints program scalability bottleneck.");
    options.add_options()("h,help", "Print help")(
        "d,line_info_dump", "Input line info directory dumped by dwarf_line_info_dump", cxxopts::value<std::string>())(
        "big", "Input measurement directory generated by jsirun with bigger scale", cxxopts::value<std::string>())(
        "small", "Input measurement directory generated by jsirun with smaller scale", cxxopts::value<std::string>())(
        "o,output", "Output result file", cxxopts::value<std::string>())(
        "k,top-k", "Load balance Top-K count.", cxxopts::value<int>()->default_value("3"))(
        "decay", "Decay factor.", cxxopts::value<double>()->default_value("0.5"))(
        "merge", "Merge factor.", cxxopts::value<double>()->default_value("0.4"))(
        "time-ratio", "Time anomaly ratio.", cxxopts::value<double>()->default_value("0.3"))(
        "ins-ratio", "Instruction number anomaly ratio.", cxxopts::value<double>()->default_value("0.4"))(
        "var-ratio", "Time standard deviation anomaly ratio.", cxxopts::value<double>()->default_value("0.3"))(
        "threshold", "Anomaly threshold.", cxxopts::value<double>()->default_value("2.0"));

    try {
        auto result = options.parse(argc, argv);
        // print help message if configured
        if (result.count("help")) {
            std::cout << options.help() << std::endl;
            exit(1);
        }
        if (result.count("big") >= 1) {
            if (result.count("big") > 2) {
                std::cout << "Warning: multiple input directory configured. Only use the last one!" << std::endl;
            }
            big_input_dir = result["big"].as<std::string>();
        } else {
            std::cout << "--big must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("small") >= 1) {
            if (result.count("small") > 2) {
                std::cout << "Warning: multiple input directory configured. Only use the last one!" << std::endl;
            }
            small_input_dir = result["small"].as<std::string>();
        } else {
            std::cout << "--small must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("line_info_dump") >= 1) {
            if (result.count("line_info_dump") > 2) {
                std::cout << "Warning: multiple input line info directory configured. Only use the last one!"
                          << std::endl;
            }
            dump_dir = result["line_info_dump"].as<std::string>();
        } else {
            std::cout << "-d or --line_info_dump must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("output") >= 1) {
            if (result.count("output") > 2) {
                std::cout << "Warning: multiple output path configured. Only use the last one!" << std::endl;
            }
            output_path = result["output"].as<std::string>();
        } else {
            output_path = "";
        }
        anomaly_threshhold = result["threshold"].as<double>();
        decay_factor       = result["decay"].as<double>();
        merge_factor       = result["merge"].as<double>();
        time_ratio         = result["time-ratio"].as<double>();
        ins_ratio          = result["ins-ratio"].as<double>();
        var_ratio          = result["var-ratio"].as<double>();
        top_k              = result["top-k"].as<int>();
        std::cout << "Configured: " << std::endl;
        std::cout << "\t" << "Bigger scale Input: " << big_input_dir << std::endl;
        std::cout << "\t" << "Smaller scale Input: " << small_input_dir << std::endl;
        std::cout << "\t" << "anomaly_threshhold: " << anomaly_threshhold << std::endl;
        std::cout << "\t" << "decay_factor: " << decay_factor << std::endl;
        std::cout << "\t" << "merge_factor: " << merge_factor << std::endl;
        std::cout << "\t" << "time_ratio: " << time_ratio << std::endl;
        std::cout << "\t" << "ins_ratio: " << ins_ratio << std::endl;
        std::cout << "\t" << "var_ratio: " << var_ratio << std::endl;
    } catch (cxxopts::exceptions::exception e) {
        std::cout << "Error: " << e.what() << std::endl;
        std::cout << options.help() << std::endl;
        exit(1);
    }
}

int main(int argc, char* argv[]) {
    parse(argc, argv);
    try {
        RecordReader* _big_reader =
            new RecordReader(big_input_dir.c_str(), SECTION_MODEL, dump_dir.empty() ? nullptr : dump_dir.c_str());
        RecordReader&          big_reader = *_big_reader;
        RecordTraceCollection& big_traces     = big_reader.get_all_traces();
        RankMetaCollection&    big_metas      = big_reader.get_all_meta_maps();
        BacktraceCollection&   big_backtraces = big_reader.get_all_backtraces();
        // Align traces for each host nodes first
        TimelineAlignment ta;
        ta.align(big_traces, big_metas);

        PBG::ProgramBehaviorGraph* bigger_graph = new PBG::ProgramBehaviorGraph(big_backtraces);
        bigger_graph->build_graph_for_processes(big_traces, big_metas, big_backtraces);
        bigger_graph->build_graph_for_program();

        RecordReader* _small_reader =
            new RecordReader(small_input_dir.c_str(), SECTION_MODEL, dump_dir.empty() ? nullptr : dump_dir.c_str());
        RecordReader&          small_reader = *_small_reader;
        RecordTraceCollection& small_traces       = small_reader.get_all_traces();
        RankMetaCollection&    small_metas        = small_reader.get_all_meta_maps();
        BacktraceCollection&   small_backtraces   = small_reader.get_all_backtraces();
        // Align traces for each host nodes first
        ta.align(small_traces, small_metas);

        PBG::ProgramBehaviorGraph* smaller_graph = new PBG::ProgramBehaviorGraph(small_backtraces);
        smaller_graph->build_graph_for_processes(small_traces, small_metas, small_backtraces);
        smaller_graph->build_graph_for_program();

        bigger_graph->differentiate(*smaller_graph, anomaly_threshhold, time_ratio, ins_ratio, var_ratio);
        bigger_graph->backtrack(decay_factor, merge_factor);
        bigger_graph->sort_nodes();
        
        if (output_path.empty()) {
            bigger_graph->print_result(top_k, std::cout);
        } else {
            std::ofstream file(output_path);
            bigger_graph->print_result(top_k, file);
        }
        

        delete bigger_graph;
        delete smaller_graph;
    } catch (fs::filesystem_error const& e) {
        std::cout << e.what() << std::endl;
        exit(1);
    }
    return 0;
}