#include "dependancy_graph.h"
#include <iostream>
#include "utils/cxxopts.hpp"
#include "record/record_reader.h"
#include <filesystem>
#include <stdio.h>
#include "../timeline/alignment.h"
#include <omp.h>
#include <chrono>

namespace fs = std::filesystem;

bool dry_run = false;
bool edges_only = false;
bool bt_only = false;
bool is_force = false;
std::string input_dir;
std::string output;
std::string dump_dir;
std::string fb_dir;
uint64_t interval;
uint64_t duration;
int mode;
uint64_t start = 0;
uint64_t end = 0;

void parse(int argc, char *argv[]) 
{
    cxxopts::Options options("timeslice_analysis_all", "Read the measurement directory generated by jsirun and generate CSV files that consolidate cpu and gpu event information based on given time slice sizes.");
    options.add_options()
        ("f,force", "Force to overwrite the output file if already exists.")
        ("h,help", "Print help")
        ("d,line_info_dump", "Input line info directory dumped by dwarf_line_info_dump", cxxopts::value<std::string>())
        ("n,dry_run", "Dry run (no file output)")
        ("e,edges_only", "Print edge info only")
        ("b,bt_only", "Print backtrace info only")
        ("s,filter_bt", "Input backtrace filter directory", cxxopts::value<std::string>())
        ("i,input", "Input measurement directory generated by jsirun", cxxopts::value<std::string>())
        ("o,output", "Output file to store the csv outputs", cxxopts::value<std::string>()->default_value("graph"))
        ("l,interval", "Time interval between two time slice(ms)", cxxopts::value<uint64_t>())
        ("u,duration", "Time duration of one time slice(ms)", cxxopts::value<uint64_t>())
        ("m,mode", "Data model (0: legacy, 1: section)", cxxopts::value<int>()->default_value("1"))
        ("start", "Start time of the analysis interval", cxxopts::value<uint64_t>()->default_value("0"))
        ("end", "End time of the analysis interval", cxxopts::value<uint64_t>()->default_value("0"));

    try {
        auto result = options.parse(argc, argv);
        // print help message if configured
        if (result.count("help")) {
            std::cout << options.help() << std::endl;
            exit(1);
        }
        if (result.count("dry_run")) {
            std::cout << "Dry run enabled. No json will be dumped" << std::endl;
            dry_run = true;
        }
        if (result.count("edges_only")) {
            std::cout << "Print edge info only" << std::endl;
            edges_only = true;
        }
        if (result.count("bt_only")) {
            std::cout << "Print bt info only" << std::endl;
            bt_only = true;
        }
        if (result.count("input") >= 1) {
            if(result.count("input") > 2) {
                std::cout << "Warning: multiple input directory configured. Only use the last one!" << std::endl;
            }
            input_dir = result["input"].as<std::string>();
        } else {
            std::cout << "-i or --input must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("line_info_dump") >= 1) {
            if (result.count("line_info_dump") > 2) {
                std::cout << "Warning: multiple input line info directory configured. Only use the last one!" << std::endl;
            }
            dump_dir = result["line_info_dump"].as<std::string>();
        } else {
            std::cout << "-d or --line_info_dump must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("filter_bt") >= 1) {
            if (result.count("filter_bt") > 2) {
                std::cout << "Warning: multiple input line info directory configured. Only use the last one!" << std::endl;
            }
            fb_dir = result["filter_bt"].as<std::string>();
        }
        if (result.count("duration") >= 1) {
            if (result.count("duration") > 2) {
                std::cout << "Warning: multiple input line info directory configured. Only use the last one!" << std::endl;
            }
            duration = result["duration"].as<uint64_t>();
        } else {
            std::cout << "-dur or --duration must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("interval") >= 1) {
            if (result.count("interval") > 2) {
                std::cout << "Warning: multiple input line info directory configured. Only use the last one!" << std::endl;
            }
            interval = result["interval"].as<uint64_t>();
        } else {
            std::cout << "-inter or --interval must be specified!" << std::endl;
            exit(1);
        }
        output = result["output"].as<std::string>();
        if (result.count("force")) {
            is_force = true;
        }
        if (result.count("mode")) {
            mode = result["mode"].as<int>();
        }
        if (result.count("start") > 0) {
            start = result["start"].as<uint64_t>();
        }
        if (result.count("end") > 0) {
            end = result["end"].as<uint64_t>();
        }
        std::cout << "Configured: " << std::endl;
        std::cout << "\t" << "Input: " << input_dir << std::endl;
        std::cout << "\t" << "Output: " << output << std::endl;
         std::cout << "\t" <<"Maximum number of threads: " << omp_get_max_threads() << std::endl;
    } catch (cxxopts::exceptions::exception e) {
        std::cout << "Error: " << e.what() << std::endl;
        std::cout << options.help() << std::endl;
        exit(1);
    }
}

int main(int argc, char *argv[]) 
{
    parse(argc, argv);
    try {
        if (fs::exists(output)) {
            if (is_force) {
                fs::remove(output);
            } else {
                std::cout << "Error: output file (" << output << ") exists!" << std::endl;
                exit(1);
            }
        }
        
        printf("JSIREADING.........\n");
        RecordReader* _reader = nullptr;
        bool enable_dump = (!dump_dir.empty());
        printf("Enable Backtrace: %d\n",enable_dump);
        RecordReader reader(input_dir.c_str(), SECTION_MODEL, dump_dir.c_str(), enable_dump, false, true);
        RecordTraceCollection& traces = reader.get_all_traces();
        RankMetaCollection& metas = reader.get_all_meta_maps();
        ExtRecordTraceCollection& rte_collection = reader.get_all_etraces();
        RankRecordTraceCollection& rank_record_collection = reader.get_main_thread_traces();
        RankExtRecordTraceCollection& rank_ext_record_collection = reader.get_all_etraces_by_rank();
        BacktraceCollection* backtraces = reader.has_backtrace() ? &reader.get_all_backtraces() : nullptr;
        // Align traces for each host nodes first
        printf("ALIGNING.........\n");
        TimelineAlignment ta;
        ta.align_for_main_thread_traces(rank_record_collection, metas);

        printf("TIME SLICING.........\n");
        DependancyGraph* graph;
        auto start_time = std::chrono::high_resolution_clock::now();
        CreateDependancyGraphSliceAll(&reader, false, interval, duration, output.c_str(), start, end, bt_only, fb_dir.c_str(), enable_dump);
        auto end_time = std::chrono::high_resolution_clock::now();
        auto duration_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count();
        auto duration_min = static_cast<double>(duration_ms) / 60000.0;
        std::cout << "TimesliceAll with omp took " << duration_min << " min" << std::endl;
        delete graph;

    } catch (const fs::filesystem_error& e) {
        std::cout << e.what() << std::endl;
        exit(1);
    }
    return 0;
}