#pragma once
#include "record/wrap_defines.h"
#include "record/record_type_traits.h"
#include "utils/compile_time.h"
#include "ral/time_detector.h"
#include <string_view>
inline pse::utils::EncodedStruct record_info[] = {
pse::utils::StructEncoder<MacroToType<event_MPI_Init>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Finalize>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Send>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Recv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Irecv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Abort>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Accumulate>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Add_error_TYPE>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Add_error_code>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Add_error_string>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Address>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Aint_add>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Aint_diff>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Allgather>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Allgatherv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Alloc_mem>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Allreduce>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Alltoall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Alltoallv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Alltoallw>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Attr_delete>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Attr_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Attr_put>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Barrier>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Bcast>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Bsend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Bsend_init>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Buffer_attach>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Buffer_detach>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cancel>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_coords>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_map>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_rank>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_shift>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cart_sub>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Cartdim_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Close_port>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_accept>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_call_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_compare>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_connect>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_create_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_create_group>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_create_keyval>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_delete_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_disconnect>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_dup>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_dup_with_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_free_keyval>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_get_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_get_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_get_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_get_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_get_parent>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_group>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_idup>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_join>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_rank>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_remote_group>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_remote_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_set_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_set_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_set_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_set_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_split>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_split_type>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Comm_test_inter>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Compare_and_swap>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Dims_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Dist_graph_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Dist_graph_create_adjacent>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Dist_graph_neighbors>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Dist_graph_neighbors_count>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Errhandler_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Errhandler_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Errhandler_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Errhandler_set>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Error_TYPE>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Error_string>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Exscan>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Fetch_and_op>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_call_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_close>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_create_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_delete>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_amode>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_atomicity>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_byte_offset>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_group>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_position>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_position_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_type_extent>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_get_view>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iread>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iread_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iread_at>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iread_at_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iread_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iwrite>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iwrite_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iwrite_at>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iwrite_at_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_iwrite_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_open>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_preallocate>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_all_begin>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_all_end>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_at>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_at_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_at_all_begin>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_at_all_end>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_ordered>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_ordered_begin>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_ordered_end>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_read_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_seek>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_seek_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_set_atomicity>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_set_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_set_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_set_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_set_view>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_sync>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_all_begin>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_all_end>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_at>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_at_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_at_all_begin>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_at_all_end>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_ordered>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_ordered_begin>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_ordered_end>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_File_write_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Finalized>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Free_mem>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Gather>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Gatherv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_accumulate>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_address>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_count>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_elements>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_elements_x>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_library_version>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_processor_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Get_version>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Graph_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Graph_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Graph_map>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Graph_neighbors>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Graph_neighbors_count>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Graphdims_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Grequest_complete>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Grequest_start>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_compare>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_difference>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_excl>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_incl>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_intersection>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_range_excl>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_range_incl>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_rank>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_translate_ranks>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Group_union>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iallgather>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iallgatherv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iallreduce>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ialltoall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ialltoallv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ialltoallw>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ibarrier>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ibcast>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ibsend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iexscan>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Igather>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Igatherv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Improbe>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Imrecv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ineighbor_allgather>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ineighbor_allgatherv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ineighbor_alltoall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ineighbor_alltoallv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ineighbor_alltoallw>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_delete>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_dup>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_get>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_get_nkeys>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_get_nthkey>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_get_valuelen>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Info_set>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Intercomm_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Intercomm_merge>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iprobe>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ireduce>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ireduce_scatter>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ireduce_scatter_block>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Irsend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Is_thread_main>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iscan>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iscatter>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Iscatterv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Isend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Issend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Keyval_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Keyval_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Lookup_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Mprobe>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Mrecv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Neighbor_allgather>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Neighbor_allgatherv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Neighbor_alltoall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Neighbor_alltoallv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Neighbor_alltoallw>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Op_commutative>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Op_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Op_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Open_port>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Pack>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Pack_external>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Pack_external_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Pack_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Pcontrol>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Probe>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Publish_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Put>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Query_thread>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Raccumulate>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Recv_init>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Reduce>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Reduce_local>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Reduce_scatter>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Reduce_scatter_block>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Register_datarep>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Request_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Request_get_status>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Rget>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Rget_accumulate>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Rput>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Rsend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Rsend_init>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Scan>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Scatter>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Scatterv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Send_init>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Sendrecv>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Sendrecv_replace>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ssend>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Ssend_init>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Start>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Startall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Status_set_cancelled>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Status_set_elements>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Status_set_elements_x>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Test>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Test_cancelled>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Testall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Testany>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Testsome>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Topo_test>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_commit>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_contiguous>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_darray>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_f90_complex>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_f90_integer>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_f90_real>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_hindexed>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_hindexed_block>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_hvector>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_indexed_block>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_keyval>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_resized>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_struct>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_create_subarray>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_delete_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_dup>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_extent>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_free_keyval>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_contents>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_envelope>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_extent>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_extent_x>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_true_extent>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_get_true_extent_x>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_hindexed>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_hvector>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_indexed>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_lb>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_match_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_set_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_set_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_size>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_size_x>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_struct>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_ub>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Type_vector>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Unpack>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Unpack_external>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Unpublish_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Wait>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Waitall>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Waitany>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Waitsome>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_allocate>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_allocate_shared>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_attach>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_call_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_complete>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_create>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_create_dynamic>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_create_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_create_keyval>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_delete_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_detach>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_fence>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_flush>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_flush_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_flush_local>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_flush_local_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_free_keyval>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_get_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_get_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_get_group>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_get_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_get_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_lock>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_lock_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_post>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_set_attr>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_set_errhandler>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_set_info>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_set_name>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_shared_query>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_start>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_sync>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_test>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_unlock>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_unlock_all>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Win_wait>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Wtick>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Wtime>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_MPI_Init_thread>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_Memory_Malloc>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_Memory_Calloc>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_Memory_Realloc>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_Memory_Free>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_PROCESS_START>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_PROCESS_EXIT>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_hipLaunchKernel>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_hipMemcpy>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_hipMemcpyAsync>>::get_encoded_struct(),
pse::utils::StructEncoder<MacroToType<event_SAMPLING_Counters>>::get_encoded_struct(),
};

inline long record_time_offset[] = {
[](){using T = MacroToType<event_MPI_Init>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Finalize>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Send>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Recv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Irecv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Abort>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Accumulate>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Add_error_TYPE>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Add_error_code>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Add_error_string>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Address>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Aint_add>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Aint_diff>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Allgather>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Allgatherv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Alloc_mem>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Allreduce>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Alltoall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Alltoallv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Alltoallw>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Attr_delete>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Attr_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Attr_put>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Barrier>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Bcast>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Bsend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Bsend_init>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Buffer_attach>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Buffer_detach>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cancel>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_coords>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_map>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_rank>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_shift>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cart_sub>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Cartdim_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Close_port>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_accept>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_call_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_compare>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_connect>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_create_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_create_group>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_create_keyval>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_delete_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_disconnect>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_dup>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_dup_with_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_free_keyval>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_get_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_get_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_get_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_get_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_get_parent>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_group>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_idup>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_join>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_rank>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_remote_group>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_remote_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_set_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_set_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_set_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_set_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_split>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_split_type>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Comm_test_inter>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Compare_and_swap>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Dims_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Dist_graph_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Dist_graph_create_adjacent>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Dist_graph_neighbors>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Dist_graph_neighbors_count>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Errhandler_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Errhandler_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Errhandler_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Errhandler_set>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Error_TYPE>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Error_string>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Exscan>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Fetch_and_op>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_call_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_close>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_create_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_delete>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_amode>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_atomicity>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_byte_offset>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_group>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_position>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_position_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_type_extent>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_get_view>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iread>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iread_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iread_at>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iread_at_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iread_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iwrite>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iwrite_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iwrite_at>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iwrite_at_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_iwrite_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_open>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_preallocate>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_all_begin>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_all_end>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_at>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_at_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_at_all_begin>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_at_all_end>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_ordered>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_ordered_begin>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_ordered_end>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_read_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_seek>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_seek_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_set_atomicity>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_set_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_set_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_set_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_set_view>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_sync>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_all_begin>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_all_end>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_at>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_at_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_at_all_begin>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_at_all_end>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_ordered>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_ordered_begin>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_ordered_end>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_File_write_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Finalized>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Free_mem>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Gather>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Gatherv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_accumulate>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_address>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_count>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_elements>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_elements_x>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_library_version>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_processor_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Get_version>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Graph_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Graph_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Graph_map>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Graph_neighbors>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Graph_neighbors_count>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Graphdims_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Grequest_complete>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Grequest_start>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_compare>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_difference>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_excl>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_incl>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_intersection>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_range_excl>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_range_incl>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_rank>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_translate_ranks>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Group_union>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iallgather>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iallgatherv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iallreduce>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ialltoall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ialltoallv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ialltoallw>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ibarrier>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ibcast>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ibsend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iexscan>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Igather>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Igatherv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Improbe>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Imrecv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ineighbor_allgather>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ineighbor_allgatherv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ineighbor_alltoall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ineighbor_alltoallv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ineighbor_alltoallw>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_delete>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_dup>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_get>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_get_nkeys>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_get_nthkey>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_get_valuelen>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Info_set>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Intercomm_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Intercomm_merge>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iprobe>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ireduce>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ireduce_scatter>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ireduce_scatter_block>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Irsend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Is_thread_main>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iscan>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iscatter>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Iscatterv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Isend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Issend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Keyval_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Keyval_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Lookup_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Mprobe>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Mrecv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Neighbor_allgather>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Neighbor_allgatherv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Neighbor_alltoall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Neighbor_alltoallv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Neighbor_alltoallw>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Op_commutative>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Op_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Op_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Open_port>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Pack>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Pack_external>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Pack_external_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Pack_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Pcontrol>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Probe>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Publish_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Put>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Query_thread>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Raccumulate>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Recv_init>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Reduce>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Reduce_local>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Reduce_scatter>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Reduce_scatter_block>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Register_datarep>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Request_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Request_get_status>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Rget>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Rget_accumulate>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Rput>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Rsend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Rsend_init>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Scan>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Scatter>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Scatterv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Send_init>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Sendrecv>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Sendrecv_replace>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ssend>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Ssend_init>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Start>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Startall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Status_set_cancelled>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Status_set_elements>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Status_set_elements_x>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Test>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Test_cancelled>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Testall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Testany>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Testsome>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Topo_test>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_commit>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_contiguous>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_darray>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_f90_complex>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_f90_integer>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_f90_real>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_hindexed>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_hindexed_block>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_hvector>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_indexed_block>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_keyval>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_resized>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_struct>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_create_subarray>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_delete_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_dup>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_extent>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_free_keyval>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_contents>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_envelope>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_extent>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_extent_x>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_true_extent>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_get_true_extent_x>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_hindexed>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_hvector>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_indexed>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_lb>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_match_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_set_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_set_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_size>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_size_x>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_struct>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_ub>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Type_vector>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Unpack>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Unpack_external>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Unpublish_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Wait>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Waitall>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Waitany>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Waitsome>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_allocate>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_allocate_shared>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_attach>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_call_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_complete>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_create>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_create_dynamic>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_create_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_create_keyval>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_delete_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_detach>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_fence>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_flush>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_flush_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_flush_local>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_flush_local_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_free_keyval>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_get_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_get_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_get_group>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_get_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_get_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_lock>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_lock_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_post>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_set_attr>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_set_errhandler>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_set_info>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_set_name>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_shared_query>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_start>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_sync>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_test>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_unlock>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_unlock_all>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Win_wait>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Wtick>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Wtime>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_MPI_Init_thread>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_Memory_Malloc>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_Memory_Calloc>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_Memory_Realloc>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_Memory_Free>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_PROCESS_START>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_PROCESS_EXIT>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_hipLaunchKernel>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_hipMemcpy>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_hipMemcpyAsync>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
[](){using T = MacroToType<event_SAMPLING_Counters>; T t; return (char*)&pse::ral::TimeAccessor<T>::get_field(t) - (char*)&t;}(),
};

