
#include <fstream>
#include <iostream>
// #include <mpi.h>

#include <algorithm>
#include <filesystem>
#include <limits>
#include <string>
#include <unordered_map>
#include <vector>

namespace fs = std::filesystem;

#include "record/record_reader.h"
#include "utils/cxxopts.hpp"

int analyze_level = 2;

std::string              input_dirs;
std::vector<std::string> trace_dirs;
std::string              output_dir = "kernel_hotspot";
std::string              dump_dir;
int                      mode = 0;

// MPI variables
int rank;
int size;

void split(const std::string &s) {
    std::string::size_type start = 0;
    std::string::size_type end   = s.find(',');
    while (end != std::string::npos) {
        trace_dirs.push_back(s.substr(start, end - start));
        start = end + 1;
        end   = s.find(',', start);
    }
    trace_dirs.push_back(s.substr(start));
}

void parse(int argc, char *argv[]) {
    cxxopts::Options options("kernel_hotspot", "Analyze accelerator kernel function hot spot");
    options.add_options()("h,help", "Print help")("i,input", "Input measurement directory generated by jsirun",
                                                  cxxopts::value<std::string>())(
        "o,output", "Output directory of result", cxxopts::value<std::string>())(
        "m,mode", "Sort mode of analysis result (total/count)", cxxopts::value<std::string>());

    try {
        auto result = options.parse(argc, argv);
        // print help message if configured
        if (result.count("help")) {
            std::cout << options.help() << std::endl;
            exit(1);
        }
        if (result.count("input") >= 1) {
            if (result.count("input") > 2) {
                std::cout << "Warning: multiple input directory configured. Only use "
                             "the last one!"
                          << std::endl;
            }
            input_dirs = result["input"].as<std::string>();
            split(input_dirs);
        } else {
            std::cout << "-i or --input must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("output") >= 1) {
            if (result.count("output") > 2) {
                std::cout << "Warning: multiple output directory configured. Only use "
                             "the last one!"
                          << std::endl;
            }
            output_dir = result["output"].as<std::string>();
        }
        if (result.count("mode") >= 1) {
            if (result.count("mode") > 2) {
                std::cout << "Warning: multiple mode selected, use total execution "
                             "time instead!"
                          << std::endl;
            }
            if (result["mode"].as<std::string>() == "count") mode = 1;
        } else {
            std::cout << "Warning: Use total execution time as default sort mode!" << std::endl;
        }
        // if (result.count("level") >= 1) {
        //     auto level = result["num-parallel"].as<std::string>();
        //     if (level == "thread")
        //         analyze_level = 0;
        //     else if (level == "process")
        //         analyze_level = 1;
        //     else if (level == "system")
        //         analyze_level = 2;
        //     else {
        //         std::cout << "Unrecognised granularity level, use system level
        //         instead" << std::endl; analyze_level = 2;
        //     }
        // }

    } catch (cxxopts::exceptions::exception e) {
        std::cout << "Error: " << e.what() << std::endl;
        std::cout << options.help() << std::endl;
        exit(1);
    }
}

struct kernel_info {
    int    call_count = 0;
    double total_time = 0.0;
    double min_time   = std::numeric_limits<double>::max();
    double max_time   = 0.0;
};

// call count, total time
std::unordered_map<std::string, kernel_info> global_kernel_info;
double                                       time_sum            = 0.0;
size_t                                       max_kernel_name_len = 0;
int                                          core_count          = 0;

// 按 call_count 排序
std::vector<std::pair<std::string, kernel_info>> sort_by_call_count(
    const std::unordered_map<std::string, kernel_info> &info_map) {
    std::vector<std::pair<std::string, kernel_info>> sorted_vector(info_map.begin(), info_map.end());
    std::sort(sorted_vector.begin(), sorted_vector.end(),
              [](const auto &a, const auto &b) { return a.second.call_count > b.second.call_count; });
    return sorted_vector;
}

std::string print_table(const std::vector<std::pair<std::string, kernel_info>> &sorted_vector, double total) {
    std::stringstream ss;
    ss << std::left << std::setw(std::max((size_t)12, max_kernel_name_len + 1)) << "Kernel Name" << std::setw(15)
       << "Call Count" << std::setw(15) << "Min Time(ms)" << std::setw(15) << "Max Time(ms)" << std::setw(15)
       << "Total Time(ms)" << std::setw(5) << "%" << std::endl;
    ss << std::string(std::max((size_t)12, max_kernel_name_len + 1) + 65, '-') << std::endl;

    for (const auto &pair : sorted_vector) {
        const std::string &kernel_name = pair.first;
        const kernel_info &info        = pair.second;
        double             percentage  = (info.total_time / total) * 100.0;
        ss << std::left << std::setw(std::max((size_t)12, max_kernel_name_len + 1)) << kernel_name << std::setw(15)
           << info.call_count << std::fixed << std::setprecision(2) << std::setw(15) << info.min_time << std::fixed
           << std::setprecision(2) << std::setw(15) << info.max_time << std::fixed << std::setprecision(2)
           << std::setw(15) << info.total_time << std::setw(5) << std::fixed << std::setprecision(2) << percentage
           << std::endl;
    }
    return ss.str();
}

// 按 total_time 排序
std::vector<std::pair<std::string, kernel_info>> sort_by_total_time(
    const std::unordered_map<std::string, kernel_info> &info_map) {
    std::vector<std::pair<std::string, kernel_info>> sorted_vector(info_map.begin(), info_map.end());
    std::sort(sorted_vector.begin(), sorted_vector.end(),
              [](const auto &a, const auto &b) { return a.second.total_time > b.second.total_time; });
    return sorted_vector;
}

int main(int argc, char *argv[]) {

    // MPI_Init(&argc, &argv);
    // MPI_Comm_rank(MPI_COMM_WORLD, &rank);

    parse(argc, argv);
    for (const auto &dir : trace_dirs) {
        try {
            auto  _reader = new RecordReader(dir.c_str(), SECTION_MODEL, dump_dir.empty() ? nullptr : dump_dir.c_str(),
                                             false, false, false);
            auto &reader  = *_reader;
            auto &etraces = reader.get_all_etraces();
            auto &metas   = reader.get_all_meta_maps();
            auto &string_sections = reader.get_all_string_sections();

            // measurement/data.cn11749.sec-tr1954284
            // key of etrace map
            MetaDataMap::MetaValue_t *t;

            int         dev_pmu_num = 0;
            const char *dev_pmu_list;
            const char *dev_type;

            for (auto meta_it = metas.begin(); meta_it != metas.end(); ++meta_it) {
                auto meta_map = meta_it->second->getMetaMap();
                if (meta_map.contains("ACCL TRACE META") && meta_map.contains("HOST INFO")) {
                    auto accl_trace_meta_map = meta_map.at("ACCL TRACE META");
                    accl_trace_meta_map->get("ACCL_DEVICE_TYPE", &t);
                    dev_type = t->ptr;
                    accl_trace_meta_map->get("ACCL_PMU_NUM_EVENTS", &t);
                    dev_pmu_num = t->i32;
                    accl_trace_meta_map->get("ACCL_PMU_EVENT_LIST", &t);
                    dev_pmu_list = t->ptr;
                }
            }

            for (const auto &[str_id, etrace] : etraces) {
                auto trace_rank = etrace->rank();
                // printf("str_id is %s, rank is %d\n", str_id.c_str(), trace_rank);
                const int core_num = 96;
                for (int i = 0; i < core_num; ++i) {
                    if (!etrace->exist(i)) continue;
                    ++core_count;
                    for (auto it = etrace->begin(i); it != etrace->end(i); ++it) {
                        auto rec = it.get();
                        AcclRecordTrace matrix_device_trace(rec, dev_pmu_num, it.record_size(), dev_pmu_list, dev_type,
                                                            string_sections.at(str_id));
                        for (auto record_it = matrix_device_trace.begin(); record_it != matrix_device_trace.end();
                             ++record_it) {
                            auto dev_record = reinterpret_cast<record_t *>(record_it.get());
                            if (record_utils::get_record_name(dev_record) == "ACCL_ACTIVITY_kernel") {
                                char buffer[1024]  = {0};
                                auto kernel_record = reinterpret_cast<mt_record_kernel_t *>(dev_record);
                                string_sections.at(str_id)->read(buffer, kernel_record->op, 1024);
                                std::string kernel_name = std::string(buffer);
                                max_kernel_name_len     = std::max(kernel_name.size(), max_kernel_name_len);
                                double kernel_duration =
                                    (kernel_record->record.timestamps.exit - kernel_record->record.timestamps.enter)
                                    / 1800000.0;
                                if (global_kernel_info.contains(kernel_name)) {
                                    ++global_kernel_info[kernel_name].call_count;
                                    global_kernel_info[kernel_name].total_time += kernel_duration;
                                    time_sum += kernel_duration;
                                    global_kernel_info[kernel_name].max_time =
                                        std::max(kernel_duration, global_kernel_info[kernel_name].max_time);
                                    global_kernel_info[kernel_name].min_time =
                                        std::min(kernel_duration, global_kernel_info[kernel_name].min_time);
                                } else {
                                    global_kernel_info[kernel_name] = {1, kernel_duration, kernel_duration,
                                                                       kernel_duration};
                                }
                            }
                        }
                    }
                }
            }
        } catch (std::exception const &e) {
            std::cout << e.what() << std::endl;
            exit(1);
        }
    }
    std::vector<std::pair<std::string, kernel_info>> kernel_vector;
    if (mode == 0) {
        kernel_vector = sort_by_total_time(global_kernel_info);
    } else {
        kernel_vector = sort_by_call_count(global_kernel_info);
    }

    std::cout << "Writing Kernel hotspot report to " << output_dir << std::endl;
    auto report = print_table(kernel_vector, time_sum);
    // auto file   = fopen((output_dir + "/kernel_hotspot.result").c_str(), "w");
    if (fs::create_directories(output_dir)) {
        std::cout << "Directories created successfully." << std::endl;
    } else {
        std::cout << "Directories already exist ?" << std::endl;
    }
    std::ofstream file(output_dir + "/kernel_hotspot.result");
    if (file.is_open()) {
        file << report;
        // file << "Average execution time of one DSP core: " << time_sum / core_count << "ms" << std::endl;
        file.close();
        std::cout << "Kernel hotspot report at " << output_dir << "/kernel_hotspot.result" << std::endl;
    } else {
        std::cerr << "Failed to open file " << output_dir << "/kernel_hotspot.result" << std::endl;
        return 1;
    }
    // if (file == NULL) {
    // 	JSI_ERROR("Fail to open file - %s\n", (output_dir + "/kernel_hotspot.result").c_str());
    // }
    // fprintf(file, "%s", report.c_str());
    return 0;
}