#include <stdio.h>

#include <filesystem>
#include <iostream>

#include "record/record_reader.h"
#include "utils/cxxopts.hpp"

namespace fs = std::filesystem;

bool        is_dump           = false;
bool        is_force          = false;
bool        backtrace_enabled = false;
int         size              = -1;
std::string dump_dir;
std::string input_dir;
std::string output_dir;
int         mode     = 1;
bool        mpi_only = false;

void parse(int argc, char* argv[]) {
    cxxopts::Options options("jsiread", "Read the measurement directory generated by jsirun.");
    options.add_options()("b,backtrace", "Read backtrace information")("d,dump", "Dump readable outputs")(
        "f,force", "Force to remove the output directory if already exists.")("h,help", "Print help")(
        "l,line_info_dump", "Input line info directory dumped by dwarf_line_info_dump", cxxopts::value<std::string>())(
        "i,input", "Input measurement directory generated by jsirun",
        cxxopts::value<std::string>())("o,output", "Output directory to store the readable outputs",
                                       cxxopts::value<std::string>()->default_value("readable"))(
        "s,size", "Maximum number of output trace event (normal). (-1 for all events <default>)",
        cxxopts::value<int>())("m,mode", "Data model (0: legacy, 1: section)",
                               cxxopts::value<int>()->default_value("1"))("mpi_only", "Read MPI trace only");

    try {
        auto result = options.parse(argc, argv);
        // print help message if configured
        if (result.count("help")) {
            std::cout << options.help() << std::endl;
            exit(1);
        }
        if (result.count("input") >= 1) {
            if (result.count("input") > 2) {
                std::cout << "Warning: multiple input directory configured. Only use the last one!" << std::endl;
            }
            input_dir = result["input"].as<std::string>();
        } else {
            std::cout << "-i or --input must be specified!" << std::endl;
            exit(1);
        }
        if (result.count("size")) {
            size = result["size"].as<int>();
        }
        if (result.count("line_info_dump") >= 1) {
            if (result.count("line_info_dump") > 2) {
                std::cout << "Warning: multiple input line info directory configured. Only use the last one!"
                          << std::endl;
            }
            dump_dir = result["line_info_dump"].as<std::string>();
        } else {
            std::cout << "-l or --line_info_dump not specified! Runtime dwarf addr2line will be used, which will cause "
                         "a great slowdown!"
                      << std::endl;
        }
        if (result.count("output") || result.count("dump")) {
            is_dump = true;
        }
        if (is_dump) {
            output_dir = result["output"].as<std::string>();
        }
        if (result.count("force")) {
            is_force = true;
        }
        if (result.count("backtrace")) {
            backtrace_enabled = true;
        }
        if (result.count("mode")) {
            mode = result["mode"].as<int>();
        }
        if (result.count("mpi_only")) {
            mpi_only = true;
        }
        std::cout << "Configured: " << std::endl;
        std::cout << "\t" << "Input: " << input_dir << std::endl;
        std::cout << "\t" << "Output: " << (is_dump ? output_dir : std::string("<stdout>")) << std::endl;
    } catch (cxxopts::exceptions::exception e) {
        std::cout << "Error: " << e.what() << std::endl;
        std::cout << options.help() << std::endl;
        exit(1);
    }
}

int main(int argc, char* argv[]) {
    // arg parse
    parse(argc, argv);
    RecordReader* _reader       = nullptr;
    bool          enable_dbinfo = true;
    bool          mpi_only      = false;
    try {
        if (mode == 0) {
            _reader = new RecordReader(input_dir.c_str(), DATA_MODEL, dump_dir.empty() ? nullptr : dump_dir.c_str(),
                                       enable_dbinfo, mpi_only, backtrace_enabled);
        } else {
            _reader = new RecordReader(input_dir.c_str(), SECTION_MODEL, dump_dir.empty() ? nullptr : dump_dir.c_str(),
                                       enable_dbinfo, mpi_only, backtrace_enabled);
        }
        RecordReader&          reader = *_reader;
        RecordTraceCollection& traces = reader.get_all_traces();
        if (is_dump) {
            if (fs::exists(output_dir)) {
                if (is_force) {
                    fs::remove_all(output_dir);
                } else {
                    std::cout << "Error: output directory (" << output_dir << ") exists!" << std::endl;
                    exit(1);
                }
            }
            if (!fs::create_directories(output_dir)) {
                std::cout << "Error: failed to create output directory (" << output_dir << ")!" << std::endl;
                exit(1);
            }
        }
        // dump meta info first
        RankMetaCollection& metas = reader.get_all_meta_maps();
        for (const auto& pair : metas) {
            FILE* fp;
            int   rank = pair.first;
            auto& data = pair.second;
            if (is_dump) {
                std::string fn;
                if (rank >= 0) {
                    fn = output_dir + std::string("/meta.") + std::to_string(rank);
                    fp = fopen(fn.c_str(), "w");
                } else {
                    fn = output_dir + std::string("/meta.pid") + std::to_string(rank);
                    fp = fopen(fn.c_str(), "w");
                }
                if (fp == NULL) {
                    std::cout << "Error: failed to open output file " << fn << std::endl;
                    exit(1);
                }
            } else {
                fp = stdout;
            }
            std::cout << "## Meta for Rank " << rank << std::endl;
            fprintf(fp, "%s", data->to_string().c_str());
            if (is_dump) {
                fclose(fp);
            }
        }
        // dump traces
        BacktraceCollection&      backtraces = reader.get_all_backtraces();
        RecordTraceCollection&    samptraces = reader.get_all_sampling_traces();
        std::vector<RecordTrace*> rt_list;
        std::vector<int>          rank_list;
        std::vector<std::string>  id_list;
        for (auto it = traces.begin(); it != traces.end(); ++it) {
            rt_list.push_back(it->second);
            rank_list.push_back(it->second->rank());
            id_list.push_back(it->first);
        }
#pragma omp parallel for
        for (int i = 0; i < rt_list.size(); i++) {
            FILE* fp;
            int   rank = rank_list[i];
            auto  id   = id_list[i];
            if (is_dump) {
                std::string fn;
                if (rank >= 0) {
                    fn = output_dir + std::string("/result.") + std::to_string(rank);
                    fp = fopen(fn.c_str(), "w");
                } else {
                    fn = output_dir + std::string("/result.pid") + std::to_string(rank);
                    fp = fopen(fn.c_str(), "w");
                }
                if (fp == NULL) {
                    std::cout << "Error: failed to open output file " << fn << std::endl;
                    exit(1);
                }
            } else {
                fp = stdout;
            }
            std::cout << "## Rank " << rank << std::endl;
            RecordTrace* rt         = rt_list[i];
            auto         num_events = rt->num_pmu_events();
            auto&        event_list = rt->pmu_event_list();
            int          j          = 1;
            for (RecordTraceIterator it = rt->begin(); it != rt->end(); it = it.next(), ++j) {
                if (size > 0 && j > size) {
                    fprintf(fp, "## Early stop as the output length exceeds given size: %d ##\n", size);
                    break;
                }
                fprintf(fp, "=== Event %d ===\n", j);
                // Write trace data and backtraces (if exist)
                if (backtrace_enabled) {
                    fprintf(fp, "%s", RecordHelper::dump_string(it.val(), backtraces[id]).c_str());
                } else {
                    fprintf(fp, "%s", RecordHelper::dump_string(it.val()).c_str());
                }
                // Write PMU event counter values
                for (int eidx = 0; eidx < num_events; eidx++) {
                    auto&      event_name = event_list[eidx];
                    const auto enter_val  = RecordHelper::counter_val_enter(it.val(), eidx, num_events);
                    const auto exit_val   = RecordHelper::counter_val_exit(it.val(), eidx, num_events);
                    fprintf(fp, "PMU Event Counter %d(%s): (%lu, %lu, %lu)\n", eidx, event_name.c_str(), enter_val,
                            exit_val, exit_val - enter_val);
                }
            }
            if (is_dump) {
                fclose(fp);
            }
        }

        std::cout << "Processing EXT trace" << std::endl;
        bool                                          has_accl = false;
        std::unordered_map<std::string, MetaDataMap*> tmp_metaMap;

        MetaDataMap::MetaValue_t* t;
        for (auto meta_it = metas.begin(); meta_it != metas.end(); ++meta_it) {
            tmp_metaMap = meta_it->second->getMetaMap();
            if (tmp_metaMap.contains("ACCL TRACE META") && tmp_metaMap.contains("HOST INFO")) {
                has_accl = true;
                break;
            }
        }
        if (!has_accl) {
            std::cout << "No accl trace!" << std::endl;
            delete _reader;
            return 0;
        }
        auto accl_trace_meta_map = tmp_metaMap.at("ACCL TRACE META");
        accl_trace_meta_map->get("ACCL_DEVICE_TYPE", &t);
        const char* dev_type = t->ptr;

        std::unordered_map<int, int> rank2pid;
        for (auto it = metas.begin(); it != metas.end(); ++it) {
            auto metaMap = it->second->getMetaMap();
            if (!metaMap.contains("HOST INFO")) continue;
            metaMap.at("HOST INFO")->get("PID", &t);
            int pid             = t->i32;
            rank2pid[it->first] = pid;
        }

        // for (auto it = rank2pid.begin(); it != rank2pid.end(); ++it) {
        //     std::cout << "[" << it->first << ", " << it->second << "] ";
        // }
        // std::cout << std::endl;

        auto string_sections = reader.get_all_string_sections();

        auto etraces = reader.get_all_etraces();
        if (etraces.empty()) {
            delete _reader;
            return 0;
        }
        printf("etraces by rank [0] size: %u\n", reader.get_all_etraces_by_rank()[0].size());
        if (std::string(dev_type).substr(0, 6) == "MATRIX") {
            accl_trace_meta_map->get("ACCL_PMU_NUM_EVENTS", &t);
            auto dev_pmu_num = t->i32;
            accl_trace_meta_map->get("ACCL_PMU_EVENT_LIST", &t);
            auto dev_event_str = t->ptr;
            for (auto& [str_id, etrace] : etraces) {
                auto rank = etrace->rank();
                if (rank < 0) continue;
                int thread_num = 96;
#pragma omp parallel for
                for (int i = 0; i < thread_num; ++i) {
                    if (!etrace->exist(i)) continue;
                    FILE* fp;
                    if (is_dump) {
                        std::string fn;
                        if (i >= 10)
                            fn = output_dir + std::string("/ext.") + std::to_string(rank) + std::string(".")
                                 + std::to_string(i);
                        else
                            fn = output_dir + std::string("/ext.") + std::to_string(rank) + std::string(".0")
                                 + std::to_string(i);
                        fp = fopen(fn.c_str(), "w");
                        if (fp == NULL) {
                            std::cout << "Error: failed to open output file " << fn << std::endl;
                            exit(1);
                        }
                    } else {
                        fp = stdout;
                    }
                    fprintf(fp, "##EXT Trace of %s Device - Thread %d\n", dev_type, i);
                    for (auto outer_it = etrace->begin(i); outer_it != etrace->end(i); ++outer_it) {
                        auto            rec = outer_it.get();
                        AcclRecordTrace accl_record_trace(rec, dev_pmu_num, outer_it.record_size(), dev_event_str,
                                                          dev_type, string_sections[str_id]);
                        fprintf(fp, "%s", accl_record_trace.to_string().c_str());
                    }
                    if (is_dump) {
                        fclose(fp);
                    }
                }
            }
        } else if (std::string(dev_type).substr(0, 5) == "HYGON") {
            for (auto& [str_id, etrace] : etraces) {
                auto rank = etrace->rank();
                if (rank < 0) continue;
                // if (!etrace->exist(0)) continue;
                FILE* fp;
                if (is_dump) {
                    std::string fn = output_dir + std::string("/ext.") + std::to_string(rank);
                    fp             = fopen(fn.c_str(), "w");
                    if (fp == NULL) {
                        std::cout << "Error: failed to open output file " << fn << std::endl;
                        exit(1);
                    }
                } else {
                    fp = stdout;
                }
                fprintf(fp, "##EXT Trace of %s Device - MPI Rank %d\n", dev_type, rank);
                int ext_trace_id = rank2pid[rank];
                // int ext_trace_id = 0;
                for (auto outer_it = etrace->begin(ext_trace_id); outer_it != etrace->end(ext_trace_id); ++outer_it) {
                    auto rec = outer_it.get();
                    // todo: no HYGON PMU
                    AcclRecordTrace accl_record_trace(rec, 0, outer_it.record_size(), "", dev_type,
                                                      string_sections[str_id]);
                    fprintf(fp, "%s", accl_record_trace.to_string().c_str());
                }
                if (is_dump) {
                    fclose(fp);
                }
            }
        }
    } catch (fs::filesystem_error const& e) {
        std::cout << e.what() << std::endl;
        delete _reader;
        exit(1);
    }
    delete _reader;
    return 0;
}
