#include "variance.h"
#include <iostream>
#include "utils/cxxopts.hpp"
#include "record/record_reader.h"
#include <filesystem>
#include <stdio.h>
#include "../timeline/alignment.h"
#include "../graph/dependancy_graph.h"
#include <omp.h>

namespace fs = std::filesystem;

bool is_force = false;
bool enable_async_comm = true;
bool enable_heatmap = true;
bool enable_detail = false;
std::string input_dir;
std::string output_dir;
std::string ref_metric;
std::string ref_metric_opt;
uint64_t resolution_ms = 100;
bool enable_warning = false;

// trace_throw.cpp  —— 抛异常时自动打印带文件+行号的栈
#define _GNU_SOURCE
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <execinfo.h>
#include <dlfcn.h>
#include <cxxabi.h>
#include <unistd.h>

__attribute__((always_inline))
void print_backtrace_demangled() {
    // 2. 采集栈
    void *array[64];
    int size = backtrace(array, 64);

    // 3. 逐帧解析
    for (int i = 0; i < size; ++i) {
        Dl_info info;
        if (dladdr(array[i], &info) && info.dli_fname) {
            // 3.1 计算相对于模块基址的偏移
            uintptr_t offset =
                (uintptr_t)array[i] - (uintptr_t)info.dli_fbase;

            // 3.2 调 addr2line
            char cmd[512];
            snprintf(cmd, sizeof(cmd),
                     "addr2line -C -f -e %s 0x%lx 2>/dev/null",
                     info.dli_fname, offset);

            FILE *pipe = popen(cmd, "r");
            if (pipe) {
                char func[256], fileline[256];
                if (fgets(func, sizeof(func), pipe) &&
                    fgets(fileline, sizeof(fileline), pipe)) {
                    func[strcspn(func, "\n")] = 0;
                    fileline[strcspn(fileline, "\n")] = 0;

                    // 3.3 去掉 C++ 符号混淆
                    int status = -1;
                    char *demangled =
                        abi::__cxa_demangle(func, nullptr, 0, &status);
                    const char *name =
                        (status == 0) ? demangled : func;

                    fprintf(stderr, "#%-2d %s  at %s\n",
                            i, name, fileline);
                    free(demangled);
                }
                pclose(pipe);
            }
        } else {
            // 解析失败
            fprintf(stderr, "#%-2d %p\n", i, array[i]);
        }
    }
}

extern "C"
void *mmap(void *addr, size_t length, int prot, int flags, int fd, off_t offset)
{
    static void *(*real_mmap)(void*,size_t,int,int,int,off_t) =
        (decltype(real_mmap))dlsym(RTLD_NEXT, "mmap");

    void *p = real_mmap(addr, length, prot, flags, fd, offset);

    if (p == MAP_FAILED) {
        fprintf(stderr,
                "[mmap failed] addr=%p len=%zu prot=%d flags=0x%x fd=%d offset=%zu : %s\n",
                addr, length, prot, flags, fd, (size_t)offset, strerror(errno));
        print_backtrace_demangled();
    }
    return p;
}

extern "C" void
__cxa_throw(void *ex, void *ti, void (*dest)(void *))
{
    // 1. 拿到真正的 __cxa_throw
    static void (*real_throw)(void*,void*,void(*)(void*)) =
        (decltype(real_throw))dlsym(RTLD_NEXT, "__cxa_throw");

    print_backtrace_demangled();

    // 4. 继续抛
    real_throw(ex, ti, dest);
}

void parse(int argc, char *argv[]) {
    cxxopts::Options options("variance_analysis", "Read the measurement directory generated by jsirun and generate variance analysis results.");
    options.add_options()
        ("f,force", "Force to overwrite the output file if already exists.")
        ("h,help", "Print help")
        ("i,input", "Input measurement directory generated by jsirun", cxxopts::value<std::string>())
        ("o,output", "Output directory to store the variance csv outputs.",cxxopts::value<std::string>()->default_value("variance"))
        ("m,reference-metric", "Reference metric for variance analysis (default: PAPI_TOT_INS)",cxxopts::value<std::string>()->default_value("PAPI_TOT_INS"))
        ("reference-metric-add", "Optional & Additional Reference metric for variance analysis (default: NONE)",cxxopts::value<std::string>()->default_value("NONE"))
        ("no-async-comm", "Disable async communication event probes")
        ("no-heatmap", "generate heatmap data")
        ("enable-detail", "Enable detailed csv without smoothing")
        ("r,resolution", "resolution (ms) to generate heatmap", cxxopts::value<uint64_t>())
        ("enable-warning", "Enable check and warning")
        ;

    try {
        auto result = options.parse(argc, argv);
        // print help message if configured
        if (result.count("help")) {
            std::cout << options.help() << std::endl;
            exit(1);
        }
        if (result.count("enable-warning")) {
            enable_warning = true;
        }
        if (result.count("input")>=1) {
            if(result.count("input")>2) {
                std::cout << "Warning: multiple input directory configured. Only use the last one!" << std::endl;
            }
            input_dir = result["input"].as<std::string>();
        } else {
            std::cout << "-i or --input must be specified!" << std::endl;
            exit(1);
        }
        output_dir = result["output"].as<std::string>();
        if (result.count("force")) {
            is_force = true;
        }
        if (result.count("no-async-comm")) {
            enable_async_comm = false;
        }
        if (result.count("no-heatmap")) {
            enable_heatmap = false;
        }
        if (result.count("resolution")) {
            resolution_ms = result["resolution"].as<uint64_t>();
        }
        if (result.count("enable-detail")) {
            enable_detail = true;
        }
        ref_metric = result["reference-metric"].as<std::string>();
        ref_metric_opt = result["reference-metric-add"].as<std::string>();
        std::cout << "Configured: " << std::endl;
        std::cout << "\t" << "Input: " << input_dir << std::endl;
        std::cout << "\t" << "Output: " << output_dir << std::endl;
        std::cout << "\t" << "Reference metric: " << ref_metric << std::endl;
        std::cout << "\t" << "Thread Count: " << omp_get_max_threads() << std::endl;
    } catch (cxxopts::exceptions::exception &e) {
        std::cout << "Error: " << e.what() << std::endl;
        std::cout << options.help() << std::endl;
        exit(1);
    }
}

int main(int argc, char *argv[]) {
    // arg parse
    parse(argc, argv);
    try {
        if(fs::exists(output_dir)) {
            if(is_force) {
                fs::remove_all(output_dir);
            } else {
                std::cout << "Error: output directory (" << output_dir << ") exists!" << std::endl;
                exit(1);
            }
        }
        if(!fs::create_directories(output_dir)) {
            std::cout << "Error: failed to create output directory (" << output_dir << ")!" << std::endl;
            exit(1);
        }
        fs::path comm_out(output_dir);
        comm_out /= "comm.csv";
        fs::path calc_out(output_dir);
        calc_out /= "calc.csv";
        fs::path accl_calc_out(output_dir);
        accl_calc_out /= "accl_calc.csv";
        fs::path accl_memcpy_out(output_dir);
        accl_memcpy_out /= "accl_memcpy.csv";
        fs::path host_map(output_dir);
        host_map /= "host.csv";
	double ts, te;
	ts = omp_get_wtime();
        RecordReader reader(input_dir.c_str(),SECTION_MODEL,nullptr,false);
        RecordTraceCollection& traces = reader.get_all_traces();
        RankMetaCollection& metas = reader.get_all_meta_maps();
        BacktraceCollection& backtraces = reader.get_all_backtraces();
        // RecordTraceExtCollection& rte_collection = reader.get_all_ext_traces();
        StringSectionCollection& string_sections = reader.get_all_string_sections();
        RankExtRecordTraceCollection& etraces = reader.get_all_etraces_by_rank();
        
	te = omp_get_wtime();
	std::cout << "Reader Time: " << te-ts << " sec\n";
        // Align traces for each host nodes first
	ts = omp_get_wtime();
        TimelineAlignment ta;
        ta.align(traces, metas);
	te = omp_get_wtime();
	std::cout << "Align Time: " << te-ts << " sec\n";
	ts = omp_get_wtime();
        VarianceMap vmap(metas, traces, backtraces, etraces, string_sections, ref_metric, ref_metric_opt, enable_async_comm, enable_warning);
	te = omp_get_wtime();
	std::cout << "Variance Calculation Time: " << te-ts << " sec\n";
	ts = omp_get_wtime();
        if (enable_detail){
            vmap.dump_comm_csv(comm_out.c_str());
            vmap.dump_calc_csv(calc_out.c_str());
            vmap.dump_accl_calc_csv(accl_calc_out.c_str());
            vmap.dump_accl_memcpy_csv(accl_memcpy_out.c_str());
        }
        if (enable_heatmap) {
            fs::path comm_out(output_dir);
            comm_out /= "comm_heat.csv";
            fs::path calc_out(output_dir);
            calc_out /= "calc_heat.csv";
            fs::path accl_calc_out(output_dir);
            accl_calc_out /= "accl_calc_heat.csv";
            fs::path accl_memcpy_out(output_dir);
            accl_memcpy_out /= "accl_memcpy_heat.csv";
            vmap.dump_comm_heatmap(comm_out.c_str(), resolution_ms);
            vmap.dump_calc_heatmap(calc_out.c_str(), resolution_ms);
            vmap.dump_accl_calc_heatmap(accl_calc_out.c_str(), resolution_ms);
            vmap.dump_accl_memcpy_heatmap(accl_memcpy_out.c_str(), resolution_ms);
        }
        // dumping host name info
        FILE* fp = fopen(host_map.c_str(), "w");
        for (auto it = traces.begin(), ie = traces.end(); it != ie; ++it) {
            auto id = it->first;
            int rank = it->second->rank();
            MetaDataMap::MetaValue_t *t;
            const std::unordered_map<std::string, MetaDataMap *> & metaMap = metas[rank]->getMetaMap();
            metaMap.at("HOST INFO")->get("HOSTNAME", &t);
            fprintf(fp, "%d,%s\n", rank, t->ptr);
        }
        fclose(fp);
	te = omp_get_wtime();
	std::cout << "Dump Time: " << te-ts << " sec\n";
    } catch (fs::filesystem_error const& e) {
        std::cout << e.what() << std::endl;
        exit(1);
    }
    return 0;
}
